"""This type stub file was generated by pyright."""

import os

from locust._version import version as __version__
from locust.contrib.fasthttp import FastHttpUser
from locust.debug import run_single_user
from locust.shape import LoadTestShape
from locust.user import wait_time
from locust.user.sequential_taskset import SequentialTaskSet
from locust.user.task import TaskSet, tag, task
from locust.user.users import HttpUser, User
from locust.user.wait_time import between, constant, constant_pacing, constant_throughput
from locust.util.deprecation import DeprecatedHttpLocustClass as HttpLocust
from locust.util.deprecation import DeprecatedLocustClass as Locust

if os.getenv('LOCUST_PLAYWRIGHT', None): ...
if not os.getenv('LOCUST_SKIP_MONKEY_PATCH', None): ...
events = ...
__all__ = (
    'FastHttpUser',
    'HttpLocust',
    'HttpUser',
    'LoadTestShape',
    'Locust',
    'SequentialTaskSet',
    'TaskSet',
    'User',
    '__version__',
    'between',
    'constant',
    'constant_pacing',
    'constant_throughput',
    'events',
    'run_single_user',
    'tag',
    'task',
    'wait_time',
)
