"""This type stub file was generated by pyright."""

import os

from ._version import version as __version__
from .contrib.fasthttp import FastHttpUser
from .debug import run_single_user
from .shape import LoadTestShape
from .user import wait_time
from .user.sequential_taskset import SequentialTaskSet
from .user.task import TaskSet, tag, task
from .user.users import HttpUser, User
from .user.wait_time import between, constant, constant_pacing, constant_throughput
from .util.deprecation import DeprecatedHttpLocustClass as HttpLocust
from .util.deprecation import DeprecatedLocustClass as Locust

if os.getenv('LOCUST_PLAYWRIGHT', None): ...
if not os.getenv('LOCUST_SKIP_MONKEY_PATCH', None): ...
events = ...
__all__ = (
    'FastHttpUser',
    'HttpLocust',
    'HttpUser',
    'LoadTestShape',
    'Locust',
    'SequentialTaskSet',
    'TaskSet',
    'User',
    '__version__',
    'between',
    'constant',
    'constant_pacing',
    'constant_throughput',
    'events',
    'run_single_user',
    'tag',
    'task',
    'wait_time',
)
