"""This type stub file was generated by pyright."""

import sys
from typing import Any, NamedTuple

import configargparse

if sys.version_info >= (3, 11): ...
else: ...
version = ...
DEFAULT_CONFIG_FILES = ...

def exit_handler(filename) -> None: ...

class LocustArgumentParser(configargparse.ArgumentParser):
    """Drop-in replacement for `configargparse.ArgumentParser` that adds support for
    optionally exclude arguments from the UI.
    """

    def add_argument(self, *args, **kwargs) -> configargparse.Action:
        """
        This method supports the same args as ArgumentParser.add_argument(..)
        as well as the additional args below.

        Arguments:
            include_in_web_ui: If True (default), the argument will show in the UI.
            is_secret: If True (default is False) and include_in_web_ui is True, the argument will show in the UI with a password masked text input.
            is_required: If True (default is False) and include_in_web_ui is True, the argument will show in the UI as a required form field.

        Returns
        -------
            argparse.Action: the new argparse action
        """
        ...

    @property
    def args_included_in_web_ui(self) -> dict[str, configargparse.Action]: ...
    @property
    def secret_args_included_in_web_ui(self) -> dict[str, configargparse.Action]: ...
    @property
    def required_args_included_in_web_ui(self) -> dict[str, configargparse.Action]: ...

class LocustTomlConfigParser(configargparse.TomlConfigParser):
    def parse(self, stream):  # -> OrderedDict[Any, Any]:
        ...

def parse_locustfile_paths(paths: list[str]) -> list[str]:
    """
    Returns a list of relative file paths.

    Args:
        paths (list[str]): paths taken from the -f command

    Returns
    -------
        list[str]: Parsed locust file paths
    """
    ...

def download_locustfile_from_url(url: str) -> str:
    """
    Attempt to download and save locustfile from url.
    Returns path to downloaded file.
    """
    ...

def get_empty_argument_parser(add_help=..., default_config_files=...) -> LocustArgumentParser: ...
def download_locustfile_from_master(master_host: str, master_port: int) -> str: ...
def parse_locustfiles_from_master(locustfile_sources) -> list[str]: ...
def parse_locustfile_option(args=...) -> list[str]:
    """
    Construct a command line parser that is only used to parse the -f argument so that we can
    import the test scripts in case any of them adds additional command line arguments to the
    parser.

    Returns
    -------
        parsed_paths (List): List of locustfile paths
    """
    ...

def raise_argument_type_error(err_msg):  # -> type[ErrorRaisingAction]:
    class ErrorRaisingAction(configargparse.Action): ...

def timespan(time_str) -> int: ...
def positive_integer(string) -> int: ...
def json_user_config(string):  # -> list[Any]:
    ...
def setup_parser_arguments(parser):  # -> None:
    """
    Setup command-line options.

    Takes a configargparse.ArgumentParser as argument and calls it's add_argument
    for each of the supported arguments
    """
    ...

def get_parser(default_config_files=...) -> LocustArgumentParser: ...
def parse_options(args=...) -> configargparse.Namespace: ...
def default_args_dict() -> dict: ...

class UIExtraArgOptions(NamedTuple):
    default_value: str
    is_secret: bool
    is_required: bool
    help_text: str
    choices: list[str] | None = ...

def ui_extra_args_dict(args=...) -> dict[str, dict[str, Any]]:
    """Get all the UI visible arguments."""
    ...
