"""This type stub file was generated by pyright."""

from typing import TYPE_CHECKING

from locust import User
from locust.env import Environment

if TYPE_CHECKING: ...

class PrintListener:
    """Print every response (useful when debugging a single locust)."""

    def __init__(
        self, env: Environment, include_length=..., include_time=..., include_context=..., include_payload=...
    ) -> None: ...
    def on_request(
        self,
        request_type,
        name,
        response_time,
        response_length,
        exception,
        context: dict,
        start_time=...,
        response=...,
        **_kwargs,
    ):  # -> None:
        ...

_env: Environment | None = ...

def run_single_user(
    user_class: type[User],
    include_length=...,
    include_time=...,
    include_context=...,
    include_payload=...,
    loglevel: str | None = ...,
):  # -> None:
    """
    Runs a single User. Useful when you want to run a debugger.

    It creates in a new locust :py:attr:`Environment <locust.env.Environment>` and triggers any ``init`` or ``test_start`` :ref:`events <extending_locust>` as normal.

    It does **not** trigger ``test_stop`` or ``quit`` when you quit the debugger.

    It prints some info about every request to stdout, and you can get additional info using the `include_*` flags

    It also initiates logging on WARNING level (not INFO, because it could interfere with the printing of requests),
    but you can change that by passing a log level (or disabling logging entirely by passing None)
    """
    ...
