"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any, TypeVar

from configargparse import Namespace  # type: ignore[import-untyped]
from locust.dispatch import UsersDispatcher
from locust.event import Events
from locust.runners import LocalRunner, MasterRunner, Runner, WorkerRunner
from locust.shape import LoadTestShape
from locust.stats import StatsCSV
from locust.user import User
from locust.user.task import TaskSet
from locust.web import WebUI

RunnerType = TypeVar('RunnerType', bound=Runner)

class Environment:
    events: Events

    def __init__(
        self,
        *,
        user_classes: list[type[User]] | None = ...,
        shape_class: LoadTestShape | None = ...,
        tags: list[str] | None = ...,
        locustfile: str | None = ...,
        exclude_tags: list[str] | None = ...,
        events: Events | None = None,
        host: str | None = ...,
        reset_stats: bool = ...,
        stop_timeout: float | None = ...,
        catch_exceptions: bool = ...,
        parsed_options: Namespace | None = ...,
        parsed_locustfiles: list[str] | None = ...,
        available_user_classes: dict[str, User] | None = ...,
        available_shape_classes: dict[str, LoadTestShape] | None = ...,
        available_user_tasks: dict[str, list[TaskSet | Callable[..., Any]]] | None = ...,
        dispatcher_class: type[UsersDispatcher] = ...,
        profile: str | None = ...,
    ) -> None: ...
    def create_local_runner(self) -> LocalRunner:
        """Create a :class:`LocalRunner <locust.runners.LocalRunner>` instance for this Environment."""

    def create_master_runner(self, master_bind_host: str = ..., master_bind_port: int = ...) -> MasterRunner:
        """
        Create a :class:`MasterRunner <locust.runners.MasterRunner>` instance for this Environment.

        :param master_bind_host: Interface/host that the master should use for incoming worker connections.
                                 Defaults to "*" which means all interfaces.
        :param master_bind_port: Port that the master should listen for incoming worker connections on
        """

    def create_worker_runner(self, master_host: str, master_port: int) -> WorkerRunner:
        """
        Create a :class:`WorkerRunner <locust.runners.WorkerRunner>` instance for this Environment.

        :param master_host: Host/IP of a running master node
        :param master_port: Port on master node to connect to
        """

    def create_web_ui(
        self,
        host: str = ...,
        port: int = ...,
        web_base_path: str | None = ...,
        web_login: bool = ...,
        tls_cert: str | None = ...,
        tls_key: str | None = ...,
        stats_csv_writer: StatsCSV | None = ...,
        delayed_start: bool = ...,
        userclass_picker_is_active: bool = ...,
        build_path: str | None = ...,
    ) -> WebUI:
        """
        Create a `locust.web.WebUI` instance for this Environment and start running the web server.

        :param host: Host/interface that the web server should accept connections to. Defaults to ""
                     which means all interfaces
        :param port: Port that the web server should listen to
        :param web_login: If provided, an authentication page will protect the app
        :param tls_cert: An optional path (str) to a TLS cert. If this is provided the web UI will be
                         served over HTTPS
        :param tls_key: An optional path (str) to a TLS private key. If this is provided the web UI will be
                        served over HTTPS
        :param stats_csv_writer: `StatsCSV <stats_csv.StatsCSV>` instance.
        :param delayed_start: Whether or not to delay starting web UI until `start()` is called. Delaying web UI start
                              allows for adding Flask routes or Blueprints before accepting requests, avoiding errors.
        """

    def update_user_class(self, user_settings: dict[str, Any]) -> None: ...
    def update_worker_logs(self, worker_log_report: dict[str, Any]) -> None: ...
    def assign_equal_weights(self) -> None:
        """Update the user classes such that each user runs their specified tasks with equal probability."""

    @property
    def user_classes_by_name(self) -> dict[str, type[User]]: ...
