"""This type stub file was generated by pyright."""

locust_cloud_version = ...
version = ...
COMMON_OPTIONS = ...

def create_environment(
    user_classes,
    options,
    events=...,
    shape_class=...,
    locustfile=...,
    parsed_locustfiles=...,
    available_user_classes=...,
    available_shape_classes=...,
    available_user_tasks=...,
):  # -> Environment:
    """Create an Environment instance from options."""
    ...

def main():  # -> None:
    ...
