"""This type stub file was generated by pyright."""

from abc import ABCMeta, abstractmethod
from typing import TYPE_CHECKING, ClassVar

from . import User
from .runners import Runner

if TYPE_CHECKING: ...

class LoadTestShapeMeta(ABCMeta):
    """
    Meta class for the main User class. It's used to allow User classes to specify task execution
    ratio using an {task:int} dict, or a [(task0,int), ..., (taskN,int)] list.
    """

    def __new__(mcs, classname, bases, class_dict):  # -> Self:
        ...

class LoadTestShape(metaclass=LoadTestShapeMeta):
    """Base class for custom load shapes."""

    runner: Runner | None = ...
    abstract: ClassVar[bool] = ...
    use_common_options: ClassVar[bool] = ...
    def __init__(self) -> None: ...
    def reset_time(self):  # -> None:
        """Resets start time back to 0."""
        ...

    def get_run_time(self):  # -> float:
        """Calculates run time in seconds of the load test."""
        ...

    def get_current_user_count(self):  # -> int:
        """Returns current actual number of users from the runner."""
        ...

    @abstractmethod
    def tick(self) -> tuple[int, float] | tuple[int, float, list[type[User]] | None] | None:
        """
        Returns a tuple with 2 elements to control the running load test:

            user_count -- Total user count
            spawn_rate -- Number of users to start/stop per second when changing number of users
            user_classes -- None or a List of userclasses to be spawned in it tick

        If `None` is returned then the running load test will be stopped.

        """
        ...
