"""This type stub file was generated by pyright."""

from typing import TYPE_CHECKING, Any, TypedDict

import gevent
from flask import Flask
from gevent import pywsgi

from .env import Environment
from .stats import StatsCSV

if TYPE_CHECKING: ...
logger = ...
greenlet_exception_handler = ...
DEFAULT_CACHE_TIME = ...

class InputField(TypedDict, total=False):
    label: str
    name: str
    type: str | None
    default_value: bool | None
    choices: list[str] | None
    is_secret: bool | None
    is_required: bool | None
    ...

class CustomForm(TypedDict, total=False):
    inputs: list[InputField] | None
    callback_url: str
    submit_button_text: str | None
    ...

class AuthProvider(TypedDict, total=False):
    label: str | None
    callback_url: str
    icon_url: str | None
    ...

class AuthArgs(TypedDict, total=False):
    custom_form: CustomForm
    auth_providers: list[AuthProvider]
    username_password_callback: str
    error: str
    info: str
    ...

class WebUI:
    """
    Sets up and runs a Flask web app that can start and stop load tests using the
    :attr:`environment.runner <locust.env.Environment.runner>` as well as show the load test statistics
    in :attr:`environment.stats <locust.env.Environment.stats>`.
    """

    app: Flask | None = ...
    greenlet: gevent.Greenlet | None = ...
    server: pywsgi.WSGIServer | None = ...
    template_args: dict[str, Any]
    auth_args: AuthArgs
    def __init__(
        self,
        environment: Environment,
        host: str,
        port: int,
        web_base_path: str | None = ...,
        web_login: bool = ...,
        tls_cert: str | None = ...,
        tls_key: str | None = ...,
        stats_csv_writer: StatsCSV | None = ...,
        delayed_start=...,
        userclass_picker_is_active=...,
        build_path: str | None = ...,
    ) -> None:
        """
        Create WebUI instance and start running the web server in a separate greenlet (self.greenlet).

        Arguments:
        environment: Reference to the current Locust Environment
        host: Host/interface that the web server should accept connections to
        port: Port that the web server should listen to
        web_login:  Enables a login page
        tls_cert: A path to a TLS certificate
        tls_key: A path to a TLS private key
        delayed_start: Whether or not to delay starting web UI until `start()` is called. Delaying web UI start
                       allows for adding Flask routes or Blueprints before accepting requests, avoiding errors.
        """
        ...

    @property
    def login_manager(self):  # -> LoginManager:
        ...
    @login_manager.setter
    def login_manager(self, value):  # -> None:
        ...
    def start(self):  # -> None:
        ...
    def start_server(self):  # -> None:
        ...
    def stop(self):  # -> None:
        """Stop the running web server."""
        ...

    def auth_required_if_enabled(
        self, view_func
    ):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | str]:
        """
        Decorator that can be used on custom route methods that will turn on Flask Login
        authentication if the ``--web-login`` flag is used. Example::

            @web_ui.app.route("/my_custom_route")
            @web_ui.auth_required_if_enabled
            def my_custom_route():
                return "custom response"
        """
        ...

    def update_template_args(self):  # -> None:
        ...
