"""This type stub file was generated by pyright."""

def memoize(
    timeout, dynamic_timeout=...
):  # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
    """
    Memoization decorator with support for timeout.

    If dynamic_timeout is set, the cache timeout is doubled if the cached function
    takes longer time to run than the timeout time
    """
    ...
