"""This type stub file was generated by pyright."""

from typing import Any

def check_for_deprecated_task_set_attribute(class_dict: dict[str, Any]) -> None: ...
def deprecated_locust_meta_class(deprecation_message: str) -> type: ...

class DeprecatedLocustClass(
    metaclass=deprecated_locust_meta_class(  # type: ignore[misc]
        'The Locust class has been renamed to User in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
class DeprecatedHttpLocustClass(
    metaclass=deprecated_locust_meta_class(  # type: ignore[misc]
        'The HttpLocust class has been renamed to HttpUser in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
class DeprecatedFastHttpLocustClass(
    metaclass=deprecated_locust_meta_class(  # type: ignore[misc]
        'The FastHttpLocust class has been renamed to FastHttpUser in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
