"""This type stub file was generated by pyright."""

def check_for_deprecated_task_set_attribute(class_dict):  # -> None:
    ...
def deprecated_locust_meta_class(deprecation_message):  # -> type[MetaClass]:
    class MetaClass(type): ...

class DeprecatedLocustClass(
    metaclass=deprecated_locust_meta_class(
        'The Locust class has been renamed to User in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
class DeprecatedHttpLocustClass(
    metaclass=deprecated_locust_meta_class(
        'The HttpLocust class has been renamed to HttpUser in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
class DeprecatedFastHttpLocustClass(
    metaclass=deprecated_locust_meta_class(
        'The FastHttpLocust class has been renamed to FastHttpUser in version 1.0. '
        'For more info see: https://docs.locust.io/en/latest/changelog.html#changelog-1-0'
    )
): ...
