"""This type stub file was generated by pyright."""

from ..shape import LoadTestShape
from ..user import User

def is_user_class(item):  # -> bool:
    """Check if a variable is a runnable (non-abstract) User class."""
    ...

def is_shape_class(item):  # -> bool:
    """Check if a class is a LoadTestShape."""
    ...

def load_locustfile(path) -> tuple[str | None, dict[str, User], list[LoadTestShape]]:
    """
    Import given locustfile path and return (docstring, callables).

    Specifically, the locustfile's ``__doc__`` attribute (a string) and a
    dictionary of ``{'name': callable}`` containing all callables which pass
    the "is a Locust" test.
    """
    ...
