"""This type stub file was generated by pyright."""

from locust.user.task import TaskSet, tag, task
from locust.user.users import HttpUser, User

__all__ = ('HttpUser', 'TaskSet', 'User', 'tag', 'task')
