"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import TYPE_CHECKING, Protocol, TypeVar, final, overload, runtime_checkable

from locust import User

if TYPE_CHECKING: ...
logger = ...
TaskT = TypeVar('TaskT', Callable[..., None], type['TaskSet'])

@runtime_checkable
class TaskHolder(Protocol[TaskT]):
    tasks: list[TaskT]
    ...

@overload
def task(weight: TaskT) -> TaskT: ...
@overload
def task(weight: int) -> Callable[[TaskT], TaskT]: ...
def task(weight: TaskT | int = ...) -> TaskT | Callable[[TaskT], TaskT]:
    """
    Used as a convenience decorator to be able to declare tasks for a User or a TaskSet
    inline in the class. Example::

        class ForumPage(TaskSet):
            @task(100)
            def read_thread(self):
                pass

            @task(7)
            def create_thread(self):
                pass

            @task(25)
            class ForumThread(TaskSet):
                @task
                def get_author(self):
                    pass

                @task
                def get_created(self):
                    pass
    """
    ...

def tag(*tags: str) -> Callable[[TaskT], TaskT]:
    """
    Decorator for tagging tasks and TaskSets with the given tag name. You can
    then limit the test to only execute tasks that are tagged with any of the
    tags provided by the :code:`--tags` command-line argument. Example::

        class ForumPage(TaskSet):
            @tag('thread')
            @task(100)
            def read_thread(self):
                pass

            @tag('thread')
            @tag('post')
            @task(7)
            def create_thread(self):
                pass

            @tag('post')
            @task(11)
            def comment(self):
                pass
    """
    ...

def get_tasks_from_base_classes(bases, class_dict):  # -> list[Any]:
    """
    Function used by both TaskSetMeta and UserMeta for collecting all declared tasks
    on the TaskSet/User class and all its base classes.
    """
    ...

def filter_tasks_by_tags(
    task_holder: type[TaskHolder],
    tags: set[str] | None = ...,
    exclude_tags: set[str] | None = ...,
    checked: dict[TaskT, bool] | None = ...,
):  # -> None:
    """
    Function used by Environment to recursively remove any tasks/TaskSets from a TaskSet/User that
    shouldn't be executed according to the tag options.
    """
    ...

class TaskSetMeta(type):
    """
    Meta class for the main User class. It's used to allow User classes to specify task execution
    ratio using an {task:int} dict, or a [(task0,int), ..., (taskN,int)] list.
    """

    def __new__(mcs, classname, bases, class_dict):  # -> Self:
        ...

class TaskSet(metaclass=TaskSetMeta):
    """
    Class defining a set of tasks that a User will execute.

    When a TaskSet starts running, it will pick a task from the *tasks* attribute,
    execute it, and then sleep for the number of seconds returned by its *wait_time*
    function. If no wait_time method has been declared on the TaskSet, it'll call the
    wait_time function on the User by default. It will then schedule another task
    for execution and so on.

    TaskSets can be nested, which means that a TaskSet's *tasks* attribute can contain
    another TaskSet. If the nested TaskSet is scheduled to be executed, it will be
    instantiated and called from the currently executing TaskSet. Execution in the
    currently running TaskSet will then be handed over to the nested TaskSet which will
    continue to run until it throws an InterruptTaskSet exception, which is done when
    :py:meth:`TaskSet.interrupt() <locust.TaskSet.interrupt>` is called. (execution
    will then continue in the first TaskSet).
    """

    tasks: list[TaskSet | Callable] = ...
    min_wait: float | None = ...
    max_wait: float | None = ...
    wait_function = ...
    _user: User
    _parent: User
    def __init__(self, parent: User) -> None: ...
    @property
    def user(self) -> User:
        """:py:class:`User <locust.User>` instance that this TaskSet was created by."""
        ...

    @property
    def parent(self):  # -> User:
        """Parent TaskSet instance of this TaskSet (or :py:class:`User <locust.User>` if this is not a nested TaskSet)."""
        ...

    def on_start(self) -> None:
        """Called when a User starts executing this TaskSet."""
        ...

    def on_stop(self):  # -> None:
        """
        Called when a User stops executing this TaskSet. E.g. when TaskSet.interrupt() is called
        or when the User is killed.
        """
        ...

    @final
    def run(self): ...
    def execute_next_task(self):  # -> None:
        ...
    def execute_task(self, task):  # -> None:
        ...
    def schedule_task(self, task_callable, first=...):  # -> None:
        """
        Add a task to the User's task execution queue.

        :param task_callable: User task to schedule.
        :param first: Optional keyword argument. If True, the task will be put first in the queue.
        """
        ...

    def get_next_task(self):  # -> TaskSet | Callable[..., Any]:
        ...
    def wait_time(self):  # -> float | Literal[0]:
        """
        Method that returns the time (in seconds) between the execution of tasks.

        Example::

            from locust import TaskSet, between
            class Tasks(TaskSet):
                wait_time = between(3, 25)
        """
        ...

    def wait(self):  # -> None:
        """
        Make the running user sleep for a duration defined by the Locust.wait_time
        function (or TaskSet.wait_time function if it's been defined).

        The user can also be killed gracefully while it's sleeping, so calling this
        method within a task makes it possible for a user to be killed mid-task, even if you've
        set a stop_timeout. If this behaviour is not desired you should make the user wait using
        gevent.sleep() instead.
        """
        ...

    def interrupt(self, reschedule=...):
        """
        Interrupt the TaskSet and hand over execution control back to the parent TaskSet.

        If *reschedule* is True (default), the parent User will immediately re-schedule,
        and execute, a new task.
        """
        ...

    @property
    def client(self):
        """Shortcut to the client :py:attr:`client <locust.User.client>` attribute of this TaskSet's :py:class:`User <locust.User>`."""
        ...

class DefaultTaskSet(TaskSet):
    """
    Default root TaskSet that executes tasks in User.tasks.
    It executes tasks declared directly on the Locust with the user instance as the task argument.
    """

    def get_next_task(self):  # -> TaskSet | Callable[..., Any]:
        ...
    def execute_task(self, task):  # -> None:
        ...
