"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import final

from gevent.pool import Group
from locust.user.task import TaskSet
from urllib3 import PoolManager

logger = ...

class UserMeta(type):
    """
    Meta class for the main User class. It's used to allow User classes to specify task execution
    ratio using an {task:int} dict, or a [(task0,int), ..., (taskN,int)] list.
    """

    def __new__(mcs, classname, bases, class_dict):  # -> Self:
        ...

class User(metaclass=UserMeta):
    """
    Represents a "user" which is to be spawned and attack the system that is to be load tested.

    The behaviour of this user is defined by its tasks. Tasks can be declared either directly on the
    class by using the :py:func:`@task decorator <locust.task>` on methods, or by setting
    the :py:attr:`tasks attribute <locust.User.tasks>`.

    This class should usually be subclassed by a class that defines some kind of client. For
    example when load testing an HTTP system, you probably want to use the
    :py:class:`HttpUser <locust.HttpUser>` class.
    """

    host: str | None = ...
    min_wait = ...
    max_wait = ...
    wait_time = ...
    wait_function = ...
    tasks: list[TaskSet | Callable] = ...
    weight: float = ...
    fixed_count: int = ...
    abstract: bool = ...
    def __init__(self, environment) -> None: ...
    def on_start(self) -> None:
        """Called when a User starts running."""
        ...

    def on_stop(self):  # -> None:
        """Called when a User stops running (is killed)."""
        ...

    @final
    def run(self):  # -> None:
        ...
    def wait(self):  # -> None:
        """
        Make the running user sleep for a duration defined by the User.wait_time
        function.

        The user can also be killed gracefully while it's sleeping, so calling this
        method within a task makes it possible for a user to be killed mid-task even if you've
        set a stop_timeout. If this behaviour is not desired, you should make the user wait using
        gevent.sleep() instead.
        """
        ...

    def start(self, group: Group):  # -> Greenlet[Callable[..., Any], Any]:
        """
        Start a greenlet that runs this User instance.

        :param group: Group instance where the greenlet will be spawned.
        :type group: gevent.pool.Group
        :returns: The spawned greenlet.
        """
        ...

    def stop(self, force: bool = ...):  # -> bool:
        """
        Stop the user greenlet.

        :param force: If False (the default) the stopping is done gracefully by setting the state to LOCUST_STATE_STOPPING
                      which will make the User instance stop once any currently running task is complete and on_stop
                      methods are called. If force is True the greenlet will be killed immediately.
        :returns: True if the greenlet was killed immediately, otherwise False
        """
        ...

    @property
    def group(self):  # -> Group:
        ...
    @property
    def greenlet(self):  # -> Greenlet[Callable[..., Any], Any] | None:
        ...
    def context(self) -> dict:
        """
        Adds the returned value (a dict) to the context for :ref:`request event <request_context>`.
        Override this in your User class to customize the context.
        """
        ...

    @classmethod
    def json(cls):  # -> dict[str, str | float | int | list[str] | None]:
        ...
    @classmethod
    def fullname(cls) -> str:
        """Fully qualified name of the user class, e.g. my_package.my_module.MyUserClass."""
        ...

class HttpUser(User):
    """
    Represents an HTTP "user" which is to be spawned and attack the system that is to be load tested.

    The behaviour of this user is defined by its tasks. Tasks can be declared either directly on the
    class by using the :py:func:`@task decorator <locust.task>` on methods, or by setting
    the :py:attr:`tasks attribute <locust.User.tasks>`.

    This class creates a *client* attribute on instantiation which is an HTTP client with support
    for keeping a user session between requests.
    """

    abstract: bool = ...
    pool_manager: PoolManager | None = ...
    def __init__(self, *args, **kwargs) -> None: ...
