"""This type stub file was generated by pyright."""

from collections.abc import Callable
from typing import Any

def between(min_wait: float, max_wait: float) -> Callable[..., Any]:
    """Return a function that will return a random number between min_wait and max_wait.

    Example
    -------
    .. code-block:: python
        class MyUser(User):
            # wait between 3.0 and 10.5 seconds after each task
            wait_time = between(3.0, 10.5)
    """
    ...

def constant(wait_time: float) -> Callable[..., Any]:
    """Return a function that just returns the number specified by the wait_time argument.

    Example
    -------
    .. code-block:: python

        class MyUser(User):
            wait_time = constant(3)
    """
    ...

def constant_pacing(wait_time: float) -> Callable[..., int]:
    """Return a function that will track the run time of the tasks.

    For each time it's called, the function will return a wait time that will try to make the total time between task
    execution equal to the time specified by the `wait_time` argument.

    In the following example the task will always be executed once every 10 seconds, no matter
    the task execution time:

    ```python
    class MyUser(User):
        wait_time = constant_pacing(10)
        @task
        def my_task(self):
            time.sleep(random.random())
    ```

    If a task execution exceeds the specified wait_time, the wait will be 0 before starting
    the next task.
    """

def constant_throughput(task_runs_per_second: int) -> Callable[..., int]:
    """Return a function that will track the run time of the tasks.

    For each time it's called, the function will return a wait time that will try to make the number of task runs per
    second execution equal to the time specified by the task_runs_per_second argument.

    If you have multiple requests in a task your RPS will of course be higher than the
    specified throughput.

    This is the mathematical inverse of constant_pacing.

    In the following example the task will always be executed once every 10 seconds, no matter
    the task execution time:

    ```python
    class MyUser(User):
        wait_time = constant_throughput(0.1)
        @task
        def my_task(self):
            time.sleep(random.random())
    ```

    If a task execution exceeds the specified wait_time, the wait will be 0 before starting
    the next task.
    """
    ...
