"""This type stub file was generated by pyright."""

from __future__ import annotations

from collections.abc import Callable, Generator
from contextlib import contextmanager
from typing import TYPE_CHECKING, Any, TypedDict

from geventhttpclient.client import HTTPClientPool  # type: ignore[import-not-found]
from geventhttpclient.header import Headers  # type: ignore[import-not-found]
from geventhttpclient.response import HTTPSocketPoolResponse  # type: ignore[import-not-found]
from geventhttpclient.useragent import (  # type: ignore[import-not-found]
    CompatRequest,
    CompatResponse,
    ConnectionError,
    UserAgent,
)
from locust.env import Environment
from locust.user import User
from typing_extensions import Unpack

if TYPE_CHECKING:
    class PostKwargs(TypedDict, total=False):
        name: str | None
        catch_response: bool
        stream: bool
        headers: dict | None
        auth: tuple[str | bytes, str | bytes] | None
        allow_redirects: bool
        context: dict
        params: dict | None
        files: dict | None
        ...

    class PutKwargs(PostKwargs, total=False):
        json: Any
        ...

    class PatchKwargs(PostKwargs, total=False):
        json: Any
        ...

    class RESTKwargs(PostKwargs, total=False):
        data: str | dict | None
        json: Any
        ...

absolute_http_url_regexp = ...
FAILURE_EXCEPTIONS = ...

def insecure_ssl_context_factory(): ...

class FastHttpSession:
    auth_header = ...
    def __init__(
        self,
        environment: Environment,
        base_url: str,
        user: User | None,
        insecure=...,
        client_pool: HTTPClientPool | None = ...,
        ssl_context_factory: Callable | None = ...,
        **kwargs,
    ) -> None: ...
    def request(
        self,
        method: str,
        url: str,
        name: str | None = ...,
        data: str | dict | None = ...,
        catch_response: bool = ...,
        stream: bool = ...,
        headers: dict | None = ...,
        auth: tuple[str | bytes, str | bytes] | None = ...,
        json: Any = ...,
        allow_redirects: bool = ...,
        context: dict = ...,
        **kwargs,
    ) -> ResponseContextManager | FastResponse:
        """
        Send and HTTP request
        Returns :py:class:`locust.contrib.fasthttp.FastResponse` object.

        :param method: method for the new :class:`Request` object.
        :param url: path that will be concatenated with the base host URL that has been specified.
            Can also be a full URL, in which case the full URL will be requested, and the base host
            is ignored.
        :param name: (optional) An argument that can be specified to use as label in Locust's
            statistics instead of the URL path. This can be used to group different URL's
            that are requested into a single entry in Locust's statistics.
        :param catch_response: (optional) Boolean argument that, if set, can be used to make a request
            return a context manager to work as argument to a with statement. This will allow the
            request to be marked as a fail based on the content of the response, even if the response
            code is ok (2xx). The opposite also works, one can use catch_response to catch a request
            and then mark it as successful even if the response code was not (i.e. 500 or 404).
        :param data: (optional) String/bytes to send in the body of the request.
        :param json: (optional) Json to send in the body of the request.
            Automatically sets Content-Type and Accept headers to "application/json".
            Only used if data is not set.
        :param headers: (optional) Dictionary of HTTP Headers to send with the request.
        :param auth: (optional) Auth (username, password) tuple to enable Basic HTTP Auth.
        :param stream: (optional) If set to true the response body will not be consumed immediately
            and can instead be consumed by accessing the stream attribute on the Response object.
            Another side effect of setting stream to True is that the time for downloading the response
            content will not be accounted for in the request time that is reported by Locust.
        :param allow_redirects: (optional) Set to True by default.
        """
        ...

    def delete(self, url: str, **kwargs: Unpack[RESTKwargs]) -> ResponseContextManager | FastResponse:
        """Sends a DELETE request."""
        ...

    def get(self, url: str, **kwargs: Unpack[RESTKwargs]) -> ResponseContextManager | FastResponse:
        """Sends a GET request."""
        ...

    def iter_lines(self, url: str, method: str = ..., **kwargs) -> Generator[str]:
        """Sends a iter_lines request."""
        ...

    def head(self, url: str, **kwargs: Unpack[RESTKwargs]) -> ResponseContextManager | FastResponse:
        """Sends a HEAD request."""
        ...

    def options(self, url: str, **kwargs: Unpack[RESTKwargs]) -> ResponseContextManager | FastResponse:
        """Sends a OPTIONS request."""
        ...

    def patch(
        self, url: str, data: str | dict | None = ..., **kwargs: Unpack[PatchKwargs]
    ) -> ResponseContextManager | FastResponse:
        """Sends a PATCH request."""
        ...

    def post(
        self, url: str, data: str | dict | None = ..., json: Any = ..., **kwargs: Unpack[PostKwargs]
    ) -> ResponseContextManager | FastResponse:
        """Sends a POST request."""
        ...

    def put(
        self, url: str, data: str | dict | None = ..., **kwargs: Unpack[PutKwargs]
    ) -> ResponseContextManager | FastResponse:
        """Sends a PUT request."""
        ...

class FastHttpUser(User):
    """
    FastHttpUser provides the same API as HttpUser, but uses geventhttpclient instead of python-requests
    as its underlying client. It uses considerably less CPU on the load generator, and should work
    as a simple drop-in-replacement in most cases.
    """

    network_timeout: float = ...
    connection_timeout: float = ...
    max_redirects: int = ...
    max_retries: int = ...
    insecure: bool = ...
    default_headers: dict | None = ...
    concurrency: int = ...
    proxy_host: str | None = ...
    proxy_port: int | None = ...
    client_pool: HTTPClientPool | None = ...
    ssl_context_factory: Callable | None = ...
    abstract: bool
    _callstack_regex = ...
    def __init__(self, environment) -> None: ...
    @contextmanager
    def rest(self, method, url, headers: dict | None = ..., **kwargs) -> Generator[RestResponseContextManager]:
        """
        A wrapper for self.client.request that:

        * Parses the JSON response to a dict called ``js`` in the response object. Marks the request as failed if the response was not valid JSON.
        * Defaults ``Content-Type`` and ``Accept`` headers to ``application/json``
        * Sets ``catch_response=True`` (so always use a :ref:`with-block <catch-response>`)
        * Catches any unhandled exceptions thrown inside your with-block, marking the sample as failed (instead of exiting the task immediately without even firing the request event)
        """
        ...

    @contextmanager
    def rest_(self, method, url, name=..., **kwargs) -> Generator[RestResponseContextManager]:
        """
        Some REST api:s use a timestamp as part of their query string (mainly to break through caches).
        This is a convenience method for that, appending a _=<timestamp> parameter automatically.
        """
        ...

class FastRequest(CompatRequest):
    payload: str | None = ...
    @property
    def body(self) -> str | None: ...

class FastResponse(CompatResponse):
    headers: Headers | None = ...
    _response: HTTPSocketPoolResponse | None = ...
    encoding: str | float | None = ...
    request: FastRequest | None = ...
    def __init__(
        self, ghc_response: HTTPSocketPoolResponse, request: FastRequest | None = ..., sent_request: str | None = ...
    ) -> None: ...
    @property
    def text(self) -> str | None:
        """Returns the text content of the response as a decoded string."""
        ...

    @property
    def url(self) -> str | None:
        """Get "response" URL, which is the same as the request URL. This is a small deviation from HttpSession, which gets the final (possibly redirected) URL."""
        ...

    def json(self) -> dict:
        """Parses the response as json and returns a dict."""
        ...

    def raise_for_status(self):  # -> None:
        """Raise any connection errors that occurred during the request."""
        ...

    @property
    def status_code(self) -> int:
        """
        We override status_code in order to return None if no valid response was
        returned. E.g. in the case of connection errors.
        """
        ...

    @property
    def ok(self):  # -> bool:
        """Returns True if :attr:`status_code` is less than 400, False if not."""
        ...

    def success(self): ...
    def failure(self, *_args, **_kwargs): ...

class ErrorResponse:
    """
    This is used as a dummy response object when geventhttpclient raises an error
    that doesn't have a real Response object attached. E.g. a socket error or similar.
    """

    headers: Headers | None = ...
    content = ...
    status_code = ...
    error: Exception | None = ...
    text: str | None = ...
    request: CompatRequest
    def __init__(self, url: str, request: CompatRequest) -> None: ...
    def raise_for_status(self): ...

class LocustBadStatusCode(ConnectionError):
    def __repr__(self):  # -> str:
        ...

class LocustUserAgent(UserAgent):
    response_type = FastResponse
    request_type = FastRequest
    valid_response_codes = ...
    def __init__(self, client_pool: HTTPClientPool | None = ..., **kwargs) -> None: ...

class ResponseContextManager(FastResponse):
    """
    A Response class that also acts as a context manager that provides the ability to manually
    control if an HTTP request should be marked as successful or a failure in Locust's statistics.

    This class is a subclass of :py:class:`FastResponse <locust.contrib.fasthttp.FastResponse>`
    with two additional methods: :py:meth:`success <locust.contrib.fasthttp.ResponseContextManager.success>`
    and :py:meth:`failure <locust.contrib.fasthttp.ResponseContextManager.failure>`.
    """

    _manual_result = ...
    _entered = ...
    def __init__(self, response, environment, request_meta) -> None: ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, exc, value, traceback):  # -> bool:
        ...
    def success(self):  # -> None:
        """
        Report the response as successful.

        Example::

            with self.client.get("/does/not/exist", catch_response=True) as response:
                if response.status_code == 404:
                    response.success()
        """
        ...

    def failure(self, exc):  # -> None:
        """
        Report the response as a failure.

        if exc is anything other than a python exception (like a string) it will
        be wrapped inside a CatchResponseError.

        Example::

            with self.client.get("/", catch_response=True) as response:
                if response.content == "":
                    response.failure("No data")
        """
        ...

class RestResponseContextManager(ResponseContextManager):
    js: dict
    error: Exception
    headers: Headers
    ...
