"""This type stub file was generated by pyright."""

from pydicom.uid import UID
from pynetdicom import events as evt
from pynetdicom._globals import ALL_TRANSFER_SYNTAXES, DEFAULT_TRANSFER_SYNTAXES
from pynetdicom._version import __version__
from pynetdicom.ae import ApplicationEntity as AE  # noqa: N817  # this is an external API
from pynetdicom.association import Association
from pynetdicom.presentation import (
    AllStoragePresentationContexts,
    ApplicationEventLoggingPresentationContexts,
    BasicWorklistManagementPresentationContexts,
    ColorPalettePresentationContexts,
    DefinedProcedureProtocolPresentationContexts,
    DisplaySystemPresentationContexts,
    HangingProtocolPresentationContexts,
    ImplantTemplatePresentationContexts,
    InstanceAvailabilityPresentationContexts,
    MediaCreationManagementPresentationContexts,
    MediaStoragePresentationContexts,
    ModalityPerformedPresentationContexts,
    NonPatientObjectPresentationContexts,
    PrintManagementPresentationContexts,
    ProcedureStepPresentationContexts,
    ProtocolApprovalPresentationContexts,
    QueryRetrievePresentationContexts,
    RelevantPatientInformationPresentationContexts,
    RTMachineVerificationPresentationContexts,
    StorageCommitmentPresentationContexts,
    StoragePresentationContexts,
    SubstanceAdministrationPresentationContexts,
    UnifiedProcedurePresentationContexts,
    VerificationPresentationContexts,
    build_context,
    build_role,
)
from pynetdicom.sop_class import register_uid

_version = ...
PYNETDICOM_UID_PREFIX = ...
PYNETDICOM_IMPLEMENTATION_VERSION: str = ...
PYNETDICOM_IMPLEMENTATION_UID: UID = ...
__all__ = [
    'AE',
    'ALL_TRANSFER_SYNTAXES',
    'DEFAULT_TRANSFER_SYNTAXES',
    'AllStoragePresentationContexts',
    'ApplicationEventLoggingPresentationContexts',
    'Association',
    'BasicWorklistManagementPresentationContexts',
    'ColorPalettePresentationContexts',
    'DefinedProcedureProtocolPresentationContexts',
    'DisplaySystemPresentationContexts',
    'HangingProtocolPresentationContexts',
    'ImplantTemplatePresentationContexts',
    'InstanceAvailabilityPresentationContexts',
    'MediaCreationManagementPresentationContexts',
    'MediaStoragePresentationContexts',
    'ModalityPerformedPresentationContexts',
    'NonPatientObjectPresentationContexts',
    'PrintManagementPresentationContexts',
    'ProcedureStepPresentationContexts',
    'ProtocolApprovalPresentationContexts',
    'QueryRetrievePresentationContexts',
    'RTMachineVerificationPresentationContexts',
    'RelevantPatientInformationPresentationContexts',
    'StorageCommitmentPresentationContexts',
    'StoragePresentationContexts',
    'SubstanceAdministrationPresentationContexts',
    'UnifiedProcedurePresentationContexts',
    'VerificationPresentationContexts',
    '__version__',
    'build_context',
    'build_role',
    'evt',
    'register_uid',
]

def debug_logger() -> None:
    """Set up the logging for debugging."""
