"""This type stub file was generated by pyright."""

from typing import TYPE_CHECKING

from pynetdicom.association import Association, ServiceUser
from pynetdicom.dul import DULServiceProvider
from pynetdicom.transport import AssociationSocket

"""ACSE service provider"""
if TYPE_CHECKING: ...
LOGGER = ...

class ACSE:
    """The Association Control Service Element (ACSE) service provider.

    The ACSE protocol handles association negotiation and establishment, and
    normal and abnormal release of an association.
    """

    def __init__(self, assoc: Association) -> None:
        """Create the ACSE service provider.

        Parameters
        ----------
        assoc : association.Association
            The Association to provide ACSE services for.
        """
        ...

    @property
    def acceptor(self) -> ServiceUser:
        """Return the *acceptor* :class:`~pynetdicom.association.ServiceUser`."""
        ...

    @property
    def acse_timeout(self) -> float | None:
        """Return the ACSE timeout (in seconds)."""
        ...

    @property
    def assoc(self) -> Association:
        """Return the parent :class:`~pynetdicom.association.Association`.

        .. versionadded:: 1.3
        """
        ...

    @property
    def dul(self) -> DULServiceProvider:
        """Return the :class:`~pynetdicom.dul.DULServiceProvider`."""
        ...

    def is_aborted(self, abort_type: str = ...) -> bool:
        """Return ``True`` if an A-ABORT and/or A-P-ABORT request has been received.

        .. versionchanged:: 1.5

            Added `abort_type` keyword parameter.

        Parameters
        ----------
        abort_type : str, optional
            The type of abort to check for. If ``'both'`` then will return
            ``True`` if an A-ABORT or A-P-ABORT is received (default). If
            ``'a-abort'`` then will return ``True`` if an A-ABORT is received,
            if ``'a-p-abort'`` then will return ``True`` if an A-P-ABORT is
            received.

        Returns
        -------
        bool
            ``True`` if an abort is received, ``False`` otherwise.
        """
        ...

    def is_release_requested(self) -> bool:
        """Return ``True`` if an A-RELEASE request has been received.

        .. versionadded:: 1.1
        """
        ...

    def negotiate_association(self) -> None:
        """Perform an association negotiation as either the *requestor* or *acceptor*."""
        ...

    def negotiate_release(self) -> None:
        """Negotiate association release.

        .. versionadded:: 1.1

        Once an A-RELEASE request has been sent any received P-DATA PDUs will
        be ignored.
        """
        ...

    @property
    def requestor(self) -> ServiceUser:
        """Return the *requestor* :class:`~pynetdicom.association.ServiceUser`."""
        ...

    def send_abort(self, source: int) -> None:
        """Send an A-ABORT request to the peer.

        Parameters
        ----------
        source : int
            The source of the abort request

            - ``0x00`` - the DUL service user
            - ``0x02`` - the DUL service provider

        Raises
        ------
        ValueError
            If the `source` value is invalid.
        """
        ...

    def send_accept(self) -> None:
        """Send an A-ASSOCIATE (accept) to the peer."""
        ...

    def send_ap_abort(self, reason: int) -> None:
        """Send an A-P-ABORT to the peer.

        Parameters
        ----------
        reason : int
            The reason for aborting the association, one of the following:

            - ``0x00`` - reason not specified
            - ``0x01`` - unrecognized PDU
            - ``0x02`` - unexpected PDU
            - ``0x04`` - unrecognized PDU parameter
            - ``0x05`` - unexpected PDU parameter
            - ``0x06`` - invalid PDU parameter value

        Raises
        ------
        ValueError
            If the `reason` value is invalid.
        """
        ...

    def send_reject(self, result: int, source: int, diagnostic: int) -> None:
        """Send an A-ASSOCIATE (reject) to the peer.

        Parameters
        ----------
        result : int
            The association rejection:

            - ``0x01`` - rejected permanent
            - ``0x02`` - rejected transient
        source : int
            The source of the rejection:

            - ``0x01`` - DUL service user
            - ``0x02`` - DUL service provider (ACSE related)
            - ``0x03`` - DUL service provider (presentation related)
        diagnostic : int
            The reason for the rejection, if the `source` is ``0x01``:

            - ``0x01`` - no reason given
            - ``0x02`` - application context name not supported
            - ``0x03`` - calling AE title not recognized
            - ``0x07`` - called AE title not recognized

            If the `source` is ``0x02``:

            - ``0x01`` - no reason given
            - ``0x02`` - protocol version not supported

            If the `source` is ``0x03``:

            - ``0x01`` - temporary congestion
            - ``0x02`` - local limit exceeded
        """
        ...

    def send_release(self, is_response: bool = ...) -> None:
        """Send an A-RELEASE (request or response) to the peer.

        Parameters
        ----------
        is_response : bool, optional
            ``True`` to send an A-RELEASE (response) to the peer, ``False``
            to send an A-RELEASE (request) to the peer (default).
        """
        ...

    def send_request(self) -> None:
        """Send an A-ASSOCIATE (request) to the peer."""
        ...

    @property
    def socket(self) -> AssociationSocket | None:
        """Return the :class:`~pynetdicom.transport.AssociationSocket`."""
        ...
