"""This type stub file was generated by pyright."""

from collections.abc import Iterator
from typing import TYPE_CHECKING

from pynetdicom.association import Association
from pynetdicom.dimse_primitives import DimsePrimitiveType
from pynetdicom.pdu_primitives import P_DATA

"""Define the DIMSE Message classes."""
if TYPE_CHECKING: ...
LOGGER = ...
_COMMAND_SET_KEYWORDS = ...
_MULTIVALUE_TAGS = ...

class DIMSEMessage:
    """Represents a DIMSE Message.

    Information is communicated across the DICOM network interface in a DICOM
    Message. A Message is composed of a Command Set followed by a
    conditional Data Set. The Command Set is used to indicate the
    operations/notifications to be performed on or with the Data Set (see
    PS3.7 6.2-3).

    ::

                primitive_to_message()       encode_msg()
        +-------------+   --->    +-----------+   --->   +-------------+
        |    DIMSE    |           |   DIMSE   |          |   P-DATA    |
        |  primitive  |           |  Message  |          |  primitive  |
        +-------------+   <---    +-----------+   <---   +-------------+
                message_to_primitive()       decode_msg()


    **Command Set**

    A Command Set is constructed of Command Elements. Command Elements contain
    the encoded values for each field of the Command Set per the semantics
    specified in the DIMSE protocol (PS3.7 9.2 and 10.2). Each Command Element
    is composed of an explicit Tag, Value Length and a Value field. The
    encoding of the Command Set shall be *Little Endian Implicit VR*.

    **Message Types**

    The following message types are available: C_STORE_RQ, C_STORE_RSP,
    C_ECHO_RQ, C_ECHO_RSP, C_FIND_RQ, C_FIND_RSP, C_GET_RQ, C_GET_RSP,
    C_MOVE_RQ, C_MOVE_RSP, C_CANCEL_RQ, N_EVENT_REPORT_RQ, N_EVENT_REPORT_RSP,
    N_SET_RQ, N_SET_RSP, N_GET_RQ, N_GET_RSP, N_ACTION_RQ, N_ACTION_RSP,
    N_CREATE_RQ, N_CREATE_RSP, N_DELETE_RQ, N_DELETE_RSP.

    Attributes
    ----------
    command_set : pydicom.dataset.Dataset
        The message Command Set information (see PS3.7 6.3).
    context_id : int
        The presentation context ID.
    data_set : io.BytesIO
        The encoded message Data Set (see PS3.7 6.3).
    encoded_command_set : io.BytesIO
        During decoding of an incoming P-DATA primitive this stores the
        encoded Command Set data from the fragments.
    """

    def __init__(self) -> None:
        """Create a new DIMSE Message."""
        ...

    def decode_msg(self, primitive: P_DATA, assoc: Association | None = ...) -> bool:
        """Convert P-DATA primitives into a ``DIMSEMessage`` sub-class.

        Decodes the data from the P-DATA service primitive (which
        may contain the results of one or more P-DATA-TF PDUs) into the
        :attr:`~DIMSEMessage.command_set` and :attr:`~DIMSEMessage.data_set`
        attributes. Also sets the :attr:`~DIMSEMessage.context_id` and
        :attr:`~DIMSEMessage.encoded_command_set` attributes of the
        ``DIMSEMessage`` sub-class object.

        Parameters
        ----------
        primitive : pdu_primitives.P_DATA
            The P-DATA service primitive to be decoded into a DIMSE message.
        assoc : association.Association, optional
            The association processing the message. This is required when:

            * :attr:`~pynetdicom._config.STORE_RECV_CHUNKED_DATASET` is
              ``True``
            * The P-DATA primitive contains part of a C-STORE-RQ message

            In this case the association is consulted for its accepted
            transfer syntax, which is included in the File Meta Information
            of the stored dataset.

        Returns
        -------
        bool
            ``True`` when the DIMSE message is completely decoded, ``False``
            otherwise.

        References
        ----------
        * DICOM Standard, Part 8, :dcm:`Annex E<part08/chapter_E.html>`
        """
        ...

    def encode_msg(self, context_id: int, max_pdu_length: int) -> Iterator[P_DATA]:
        """Yield P-DATA primitives for the current DIMSE Message.

        **Encoding**

        The encoding of the Command Set shall be *Little Endian Implicit VR*,
        while the *Data Set* will be encoded as per the agreed presentation
        context.

        A P-DATA request's PDV List parameter shall contain one or more PDVs.
        Each PDV is wholly contained in a given P-DATA request and doesn't
        span across several P-DATA request primitives.

        The fragmentation of any message results in a series of PDVs that shall
        be sent, on a given association, by a corresponding series of P-DATA
        requests preserving the ordering of the fragments of any message.
        No fragments of any other messages shall be sent until all fragments
        of the current message have been sent.

        Parameters
        ----------
        context_id : int
            The *ID* of the agreed presentation context.
        max_pdu_length : int
            The maximum PDV length (in bytes).

        Yields
        ------
        pdu_primitives.P_DATA
            The current DIMSE message as one or more P-DATA service
            primitives.

        References
        ----------
        * DICOM Standard, Part 7,
          :dcm:`Section 6.3.1<part07/sect_6.3.html#sect_6.3.1>`
        * DICOM Standard, Part 8, :dcm:`Annex E<part08/chapter_E.html>`
        """
        ...

    def message_to_primitive(self) -> DimsePrimitiveType:
        """Convert the ``DIMSEMessage`` class to a DIMSE primitive.

        Returns
        -------
        DIMSEPrimitive sub-class
            One of the DIMSE message primitives from
            :ref:`pynetdicom.dimse_primitives<api_dimse_primitives>` generated
            from the current ``DIMSEMessage`` sub-class object.
        """
        ...

    def primitive_to_message(self, primitive: DimsePrimitiveType) -> None:
        """Convert a DIMSE `primitive` to the current ``DIMSEMessage`` object.

        Parameters
        ----------
        DIMSEPrimitive sub-class
            A DIMSE message primitive from
            :ref:`pynetdicom.dimse_primitives<api_dimse_primitives>`
            to convert to the current ``DIMSEMessage`` object.
        """
        ...

class C_STORE_RQ(DIMSEMessage): ...
class C_STORE_RSP(DIMSEMessage): ...
class C_FIND_RQ(DIMSEMessage): ...
class C_FIND_RSP(DIMSEMessage): ...
class C_GET_RQ(DIMSEMessage): ...
class C_GET_RSP(DIMSEMessage): ...
class C_MOVE_RQ(DIMSEMessage): ...
class C_MOVE_RSP(DIMSEMessage): ...
class C_ECHO_RQ(DIMSEMessage): ...
class C_ECHO_RSP(DIMSEMessage): ...
class C_CANCEL_RQ(DIMSEMessage): ...
class N_EVENT_REPORT_RQ(DIMSEMessage): ...
class N_EVENT_REPORT_RSP(DIMSEMessage): ...
class N_GET_RQ(DIMSEMessage): ...
class N_GET_RSP(DIMSEMessage): ...
class N_SET_RQ(DIMSEMessage): ...
class N_SET_RSP(DIMSEMessage): ...
class N_ACTION_RQ(DIMSEMessage): ...
class N_ACTION_RSP(DIMSEMessage): ...
class N_CREATE_RQ(DIMSEMessage): ...
class N_CREATE_RSP(DIMSEMessage): ...
class N_DELETE_RQ(DIMSEMessage): ...
class N_DELETE_RSP(DIMSEMessage): ...

_MESSAGE_TYPES = ...
_DATASET_KEYWORDS = ...
