"""This type stub file was generated by pyright."""

import queue
from threading import Thread
from typing import TYPE_CHECKING

from pynetdicom.association import Association
from pynetdicom.pdu import _PDUType  # pyright: ignore[reportPrivateUsage]
from pynetdicom.pdu_primitives import _PDUPrimitiveType  # pyright: ignore[reportPrivateUsage]
from pynetdicom.transport import T_CONNECT

if TYPE_CHECKING:
    _QueueType = queue.Queue[_PDUPrimitiveType | T_CONNECT]
LOGGER = ...

class DULServiceProvider(Thread):
    """The DICOM Upper Layer Service Provider.

    Attributes
    ----------
    artim_timer : timer.Timer
        The :dcm:`ARTIM<part08/chapter_9.html#sect_9.1.5>` timer.
    socket : transport.AssociationSocket
        A wrapped `socket
        <https://docs.python.org/3/library/socket.html#socket-objects>`_
        object used to communicate with the peer.
    to_provider_queue : queue.Queue
        Queue of primitives received from the peer to be processed by the service user.
    to_user_queue : queue.Queue
        Queue of processed PDUs for the DUL service user.
    event_queue : queue.Queue
        List of queued events to be processed by the state machine.
    state_machine : fsm.StateMachine
        The DICOM Upper Layer's State Machine.
    """

    def __init__(self, assoc: Association) -> None:
        """Create a new DUL service provider for `assoc`.

        Parameters
        ----------
        assoc : association.Association
            The DUL's parent :class:`~pynetdicom.association.Association`
            instance.
        """
        ...

    @property
    def assoc(self) -> Association:
        """Return the parent :class:`~pynetdicom.association.Association`."""
        ...

    def idle_timer_expired(self) -> bool:
        """Return ``True`` if the network idle timer has expired."""
        ...

    def kill_dul(self) -> None:
        """Kill the DUL reactor and stop the thread."""
        ...

    @property
    def network_timeout(self) -> float | None:
        """Return the network timeout (in seconds)."""
        ...

    def peek_next_pdu(self) -> _PDUPrimitiveType | None:
        """Check the next PDU to be processed."""
        ...

    def receive_pdu(self, wait: bool = ..., timeout: float | None = ...) -> _PDUPrimitiveType | None:
        """Return an item from the queue if one is available.

        Get the next service primitive to be processed out of the queue of items sent
        from the DUL service provider to the service user

        Parameters
        ----------
        wait : bool, optional
            If `wait` is ``True`` and `timeout` is ``None``, blocks until an
            item is available. If `timeout` is a positive number, blocks at
            most `timeout` seconds. Otherwise returns an item if one is
            immediately available.
        timeout : int or None
            See the definition of `wait`

        Returns
        -------
        A_ASSOCIATE | A_RELEASE | A_ABORT | A_P_ABORT | None
            The next primitive in the :attr:`~DULServiceProvider.to_user_queue`, or
            ``None`` if the queue is empty.
        """
        ...

    def run_reactor(self) -> None:
        """Run the DUL reactor.

        The main :class:`threading.Thread` run loop. Runs constantly, checking
        the connection for incoming data. When incoming data is received it
        categorizes it and add its to the
        :attr:`~DULServiceProvider.to_user_queue`.
        """
        ...

    def send_pdu(self, primitive: _PDUPrimitiveType) -> None:
        """Place a primitive in the provider queue to be sent to the peer.

        Primitives are converted to the corresponding PDU and encoded before
        sending.

        Parameters
        ----------
        primitive : pdu_primitives.PDU sub-class
            A service primitive, one of:

            .. currentmodule:: pynetdicom.pdu_primitives

            * :class:`A_ASSOCIATE`
            * :class:`A_RELEASE`
            * :class:`A_ABORT`
            * :class:`A_P_ABORT`
            * :class:`P_DATA`
        """
        ...

    def stop_dul(self) -> bool:
        """Stop the reactor if current state is ``'Sta1'``.

        Returns
        -------
        bool
            ``True`` if ``'Sta1'`` and the reactor has stopped, ``False``
            otherwise
        """
        ...

_PDU_TYPES: dict[bytes, tuple[type[_PDUType], str]] = ...
