"""This type stub file was generated by pyright."""

from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any, NamedTuple, ParamSpec

from pydicom.dataset import Dataset, FileMetaDataset
from pydicom.tag import BaseTag
from pynetdicom.association import Association

LOGGER = ...
_BasicReturnType = Dataset | int
_DatasetReturnType = tuple[_BasicReturnType, Dataset | None]
_IteratorType = Iterator[tuple[_BasicReturnType, Dataset | None]]

class NotificationEvent(NamedTuple):
    """Representation of a notification event.

    .. versionadded:: 1.3

    Possible notification events are:

    * :class:`EVT_ABORTED`
    * :class:`EVT_ACCEPTED`
    * :class:`EVT_ACSE_RECV`
    * :class:`EVT_ACSE_SENT`
    * :class:`EVT_CONN_CLOSE`
    * :class:`EVT_CONN_OPEN`
    * :class:`EVT_DATA_RECV`
    * :class:`EVT_DATA_SENT`
    * :class:`EVT_DIMSE_RECV`
    * :class:`EVT_DIMSE_SENT`
    * :class:`EVT_ESTABLISHED`
    * :class:`EVT_FSM_TRANSITION`
    * :class:`EVT_PDU_RECV`
    * :class:`EVT_PDU_SENT`
    * :class:`EVT_REJECTED`
    * :class:`EVT_RELEASED`
    * :class:`EVT_REQUESTED`
    """

    name: str
    description: str
    is_intervention: bool = ...
    is_notification: bool = ...
    def __str__(self) -> str:
        """Define the string representation of the class."""

EVT_ABORTED = ...
EVT_ACCEPTED = ...
EVT_ACSE_RECV = ...
EVT_ACSE_SENT = ...
EVT_CONN_CLOSE = ...
EVT_CONN_OPEN = ...
EVT_DATA_RECV = ...
EVT_DATA_SENT = ...
EVT_DIMSE_RECV = ...
EVT_DIMSE_SENT = ...
EVT_ESTABLISHED = ...
EVT_FSM_TRANSITION = ...
EVT_PDU_RECV = ...
EVT_PDU_SENT = ...
EVT_REJECTED = ...
EVT_RELEASED = ...
EVT_REQUESTED = ...

class InterventionEvent(NamedTuple):
    """Representation of an intervention event.

    .. versionadded:: 1.3

    Possible intervention events are:

    * :class:`EVT_ASYNC_OPS`
    * :class:`EVT_SOP_COMMON`
    * :class:`EVT_SOP_EXTENDED`
    * :class:`EVT_USER_ID`
    * :class:`EVT_C_ECHO`
    * :class:`EVT_C_FIND`
    * :class:`EVT_C_GET`
    * :class:`EVT_C_MOVE`
    * :class:`EVT_C_STORE`
    * :class:`EVT_N_ACTION`
    * :class:`EVT_N_CREATE`
    * :class:`EVT_N_DELETE`
    * :class:`EVT_N_EVENT_REPORT`
    * :class:`EVT_N_GET`
    * :class:`EVT_N_SET`
    """

    name: str
    description: str
    is_intervention: bool = ...
    is_notification: bool = ...
    def __str__(self) -> str:
        """Define the string representation of the class."""

EVT_ASYNC_OPS = ...
EVT_SOP_COMMON = ...
EVT_SOP_EXTENDED = ...
EVT_USER_ID = ...
EVT_C_ECHO = ...
EVT_C_FIND = ...
EVT_C_GET = ...
EVT_C_MOVE = ...
EVT_C_STORE = ...
EVT_N_ACTION = ...
EVT_N_CREATE = ...
EVT_N_DELETE = ...
EVT_N_EVENT_REPORT = ...
EVT_N_GET = ...
EVT_N_SET = ...
_INTERVENTION_EVENTS = ...
_NOTIFICATION_EVENTS = ...

P = ParamSpec('P')
Handler = Callable[P, int | Dataset]
_HandlerAndParams = tuple[Handler[P], tuple[Any, ...] | None]

HandlerArgType = list[_HandlerAndParams[P]] | _HandlerAndParams[P]
EventType = NotificationEvent | InterventionEvent
EventHandlerType = tuple[EventType, Handler[P]] | tuple[EventType, Handler[P], tuple[Any, ...] | None]

def get_default_handler(event: InterventionEvent) -> Callable[[Event], Any]:
    """Return the default handler for an intervention `event`.

    .. versionadded:: 1.3
    """

def trigger(assoc: Association, event: EventType, attrs: dict[str, Any] | None = ...) -> Any | None:
    """Trigger an `event` and call any bound handler(s).

    .. versionadded:: 1.3

    Notification events can be bound to multiple handlers, intervention events
    can only be bound to a single handler.

    **Special Attributes**

    If `attrs` contains:

    * `_is_cancelled` key then :attr:`Event.is_cancelled` will be hooked into
      the value's callable function.
    * a C-FIND, C-GET or C-MOVE `request` key then :attr:`Event.identifier`
      will return the decoded *Identifier* parameter value.
    * a C-STORE `request` key then :attr:`Event.dataset` will return the
      decoded *Data Set* parameter value.
    * an N-ACTION `request` key then :attr:`Event.action_information` will
      return the decoded *Action Information* parameter value.
    * an N-CREATE `request` key then :attr:`Event.attribute_list` will return
      the decoded *Attribute List* parameter value.
    * an N-EVENT-REPORT `request` key then :attr:`Event.event_information` will
      return the decoded *Event Information* parameter value.
    * an N-SET `request` key then :attr:`Event.modification_list` will return
      the decoded *Modification List* parameter value.

    Parameters
    ----------
    assoc : assoc.Association
        The association in which the event occurred.
    event : events.NotificationEvent or events.InterventionEvent
        The event to trigger.
    attrs : dict, optional
        The attributes to set in the :class:`Event` instance that is passed to
        the event's corresponding handler functions as
        ``{attribute name : value}``, default ``{}``.

    Raises
    ------
    Exception
        If an exception occurs in an intervention event handler then the
        exception will be raised. If an exception occurs in a notification
        handler then the exception will be caught and logged instead.
    """

class Event:
    """Representation of an event.

    .. versionadded:: 1.3

    .. warning::

       Some of :class:`Event`'s attributes are set dynamically when an event is
       triggered and are available only for a specific event. For example, the
       ``Event.context`` attribute is only available for events such as
       ``evt.EVT_C_ECHO``, ``evt.EVT_C_STORE``, etc. See the
       :ref:`handler documentation<api_events>` for a list of what attributes
       are available for a given event.

    Attributes
    ----------
    assoc : association.Association
        The association in which the event occurred.
    timestamp : datetime.datetime
        The date/time the event was created. Will be slightly before or after
        the actual event that this object represents.
    """

    def __init__(self, assoc: Association, event: EventType, attrs: dict[str, Any] | None = ...) -> None:
        """Create a new Event.

        Parameters
        ----------
        assoc : association.Association
            The association in which the event occurred.
        event : events.NotificationEvent or events.InterventionEvent
            The representation of the event that occurred.
        attrs : dict, optional
            The ``{attribute : value}`` pairs to use to set the
            :class:`Event`'s  attributes.
        """

    @property
    def action_information(self) -> Dataset:
        """Return an N-ACTION request's `Action Information` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Action Information* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-ACTION request.
        """

    @property
    def action_type(self) -> int | None:
        """Return an N-ACTION request's `Action Type ID` as an :class:`int`.

        .. versionadded:: 1.4

        Returns
        -------
        int or None
            The request's (0000,1008) *Action Type ID* value, may be ``None``
            if the peer's N-ACTION request is non-conformant.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-ACTION request.
        """

    @property
    def attribute_identifiers(self) -> list[BaseTag]:
        """Return an N-GET request's `Attribute Identifier List` as a :class:`list` of *pydicom* :class:`~pydicom.tag.BaseTag`.

        Returns
        -------
        list of pydicom.tag.BaseTag
            The (0000,1005) *Attribute Identifier List* tags, may be an empty
            list if no *Attribute Identifier List* was included in the C-GET
            request.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-GET request.
        """

    @property
    def attribute_list(self) -> Dataset:
        """Return an N-CREATE request's `Attribute List` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Attribute List* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-CREATE request.
        """

    @property
    def dataset(self) -> Dataset:
        """Return a C-STORE request's `Data Set` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Data Set* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not a C-STORE request.
        """

    @property
    def dataset_path(self) -> Path:
        """Return the path to the dataset when :attr:`~pynetdicom._config.STORE_RECV_CHUNKED_DATASET` is ``True``.

        .. versionadded:: 2.0

        Returns
        -------
        pathlib.Path
            The path to the dataset.
        """

    def encoded_dataset(self, include_meta: bool = ...) -> bytes:
        """Return the encoded C-STORE dataset sent by the peer without first decoding it.

        .. versionadded:: 2.1

        Examples
        --------
        Retrieve the encoded dataset as sent by the peer::

          def handle_store(event: pynetdicom.events.Event) -> int:
              stream: bytes = event.encoded_dataset(include_meta=False)

              return 0x0000

        Write the encoded dataset to file in the DICOM File Format without
        having to first decode it::

          def handle_store(event: pynetdicom.events.Event, dst: pathlib.Path) -> int:
              with dst.open("wb") as f:
                  f.write(event.encoded_dataset())

              return 0x0000

        Parameters
        ----------
        include_meta : bool, optional
            If ``True`` (default) then include the encoded DICOM preamble,
            prefix and file meta information with the returned bytestream.

        Returns
        -------
        bytes
            The encoded dataset as sent by the peer, with or without the file
            meta information.

        Raises
        ------
        AttributeError
            If the corresponding event is not a C-STORE request.
        """

    @property
    def event(self) -> EventType:
        """Return the corresponding event.

        .. versionadded:: 1.4

        Returns
        -------
        events.InterventionEvent or events.NotificationEvent
            The corresponding event as a
            :func:`namedtuple<collections.namedtuple>`.
        """

    @property
    def event_information(self) -> Dataset:
        """Return an N-EVENT-REPORT request's `Event Information` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Event Information* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-EVENT-REPORT request.
        """

    @property
    def event_type(self) -> int | None:
        """Return an N-EVENT-REPORT request's `Event Type ID` as an :class:`int`.

        .. versionadded:: 1.4

        Returns
        -------
        int or None
            The request's (0000,1002) *Event Type ID* value, may be ``None``
            if the peer's N-EVENT-REPORT request is non-conformant.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-EVENT-REPORT request.
        """

    @property
    def file_meta(self) -> FileMetaDataset:
        r"""Return a *pydicom* :class:`~pydicom.dataset.Dataset` with the :dcm:`File Meta Information<part10/chapter_7.html#sect_7.1>` for a C-STORE request's `Data Set`.

        Contains the following File Meta Information elements:

        * (0002,0000) *File Meta Information Group Length* - set as ``0``, will
          be updated with the correct value during write
        * (0002,0001) *File Meta Information Version* - set as ``0x0001``
        * (0002,0002) *Media Storage SOP Class UID* - set from the request's
          *Affected SOP Class UID*
        * (0002,0003) *Media Storage SOP Instance UID* - set from the request's
          *Affected SOP Instance UID*
        * (0002,0010) *Transfer Syntax UID* - set from the presentation context
          used to transfer the *Data Set*
        * (0002,0012) *Implementation Class UID* - set using
          :attr:`~pynetdicom.PYNETDICOM_IMPLEMENTATION_UID`
        * (0002,0013) *Implementation Version Name* - set using
          :attr:`~pynetdicom.PYNETDICOM_IMPLEMENTATION_VERSION`

        Examples
        --------
        Add the File Meta Information to the decoded *Data Set* and save it to
        the :dcm:`DICOM File Format<part10/chapter_7.html>`.

        .. code-block:: python

            >>> ds = event.dataset
            >>> ds.file_meta = event.file_meta
            >>> ds.save_as('example.dcm', write_like_original=False)

        Encode the File Meta Information in a new file and append the encoded
        *Data Set* to it. This skips having to decode/re-encode the *Data Set*
        as in the previous example (or alternatively, just use the
        :meth:`~pynetdicom.events.Event.encoded_dataset` method).

        .. code-block:: python

           >>> from pydicom.filewriter import write_file_meta_info
           >>> with open('example.dcm', 'wb') as f:
           ...     f.write(b'\x00' * 128)
           ...     f.write(b'DICM')
           ...     write_file_meta_info(f, event.file_meta)
           ...     f.write(event.request.DataSet.getvalue())

        Returns
        -------
        pydicom.dataset.Dataset
            The File Meta Information suitable for use with the decoded C-STORE
            request's *Data Set*.

        Raises
        ------
        AttributeError
            If the corresponding event is not a C-STORE request.
        """

    @property
    def identifier(self) -> Dataset:
        """Return a C-FIND, C-GET or C-MOVE request's `Identifier` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Identifier* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not a C-FIND, C-GET or C-MOVE
            request.
        """

    @property
    def is_cancelled(self) -> bool:
        """Return ``True`` if a C-CANCEL request has been received.

        Returns
        -------
        bool
            If this event corresponds to a C-FIND, C-GET or C-MOVE request
            being received by a Service Class then returns ``True`` if a
            C-CANCEL request with a *Message ID Being Responded To* parameter
            value corresponding to the *Message ID* of the service request has
            been received. If no such C-CANCEL request has been received or if
            the event is not a C-FIND, C-GET or C-MOVE request then returns
            ``False``.
        """

    @property
    def message_id(self) -> int:
        """Return a DIMSE service request's `Message ID` as :class:`int`.

        .. versionadded:: 1.5

        Returns
        -------
        int
            The request's (0000,0110) *Message ID* value.

        Raises
        ------
        AttributeError
            If the corresponding event is not one of the DIMSE service
            requests.
        """

    @property
    def modification_list(self) -> Dataset:
        """Return an N-SET request's `Modification List` as a *pydicom* :class:`~pydicom.dataset.Dataset`.

        Because *pydicom* defers data parsing during decoding until an element
        is actually required the returned :class:`~pydicom.dataset.Dataset`
        may raise an exception when any element is first accessed. It's
        therefore important that proper error handling be part of any handler
        that uses the returned :class:`~pydicom.dataset.Dataset`.

        Returns
        -------
        pydicom.dataset.Dataset
            The decoded *Modification List* dataset.

        Raises
        ------
        AttributeError
            If the corresponding event is not an N-SET request.
        """

    @property
    def move_destination(self) -> str | None:
        """Return a C-MOVE request's `Move Destination` as :class:`str`.

        .. versionadded:: 1.4

        .. versionchanged:: 2.0

            Changed to return :class:`str` and trailing spaces removed.

        Returns
        -------
        str or None
            The request's (0000,0600) *Move Destination* value, without any
            trailing padding spaces. May be ``None`` if the peer's C-MOVE
            request is non-conformant.

        Raises
        ------
        AttributeError
            If the corresponding event is not a C-MOVE request.
        """
