"""This type stub file was generated by pyright."""

from __future__ import annotations

from typing import Any

from pydicom.uid import UID
from pynetdicom.pdu_items import (
    PresentationContextItemAC,
    PresentationContextItemRQ,
    PresentationDataValueItem,
    UserInformationItem,
)
from pynetdicom.pdu_primitives import A_ABORT, A_ASSOCIATE, A_P_ABORT, A_RELEASE, P_DATA

LOGGER = ...
_PDVItem = list[PresentationDataValueItem]
UCHAR = ...
UINT2 = ...
UINT4 = ...
UNPACK_UCHAR = ...
UNPACK_UINT2 = ...
UNPACK_UINT4 = ...
PACK_UCHAR = ...
PACK_UINT2 = ...
PACK_UINT4 = ...

class PDU:
    """Base class for PDUs.

    Protocol Data Units (PDUs) are the message formats exchanged between peer
    entities within a layer. A PDU consists of protocol control information
    and user data. PDUs are constructed by mandatory fixed fields followed by
    optional variable fields that contain one or more items and/or sub-items.

    References
    ----------
    DICOM Standard, Part 8, :dcm:`Section 9.3 <part08/sect_9.3.html>`
    """

    def decode(self, bytestream: bytes) -> None:
        """Decode `bytestream` and use the result to set the field values of the PDU.

        Parameters
        ----------
        bytestream : bytes
            The PDU data to be decoded.
        """
        ...

    def encode(self) -> bytes:
        """Return the encoded PDU as :class:`bytes`.

        Returns
        -------
        bytes
            The encoded PDU.
        """
        ...

    def __eq__(self, other: Any) -> bool:
        """Return ``True`` if `self` equals `other`."""
        ...

    def __len__(self) -> int:
        """Return the total length of the encoded PDU as :class:`int`."""
        ...

    def __ne__(self, other: Any) -> bool:
        """Return ``True`` if `self` does not equal `other`."""
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as :class:`int`."""
        ...

    @property
    def pdu_type(self) -> int:
        """Return the *PDU Type* field value as :class:`int`."""
        ...

class A_ASSOCIATE_RQ(PDU):
    """An A-ASSOCIATE-RQ PDU.

    An A-ASSOCIATE-RQ PDU is sent by an association requestor to initiate
    association negotiation with an acceptor.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x01``).
    protocol_version : int
        The *Protocol Version* field value (``0x01``).
    variable_items : list
        A list containing the A-ASSOCIATE-RQ's *Variable Items*. Contains
        one Application Context item, one or more Presentation Context items
        and one User Information item. The order of the items is not
        guaranteed.

    Notes
    -----
    An A-ASSOCIATE-RQ PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x01``)
    * PDU length (1)
    * Protocol version (1, default value, ``0x01``)
    * Called AE title (1)
    * Calling AE title (1)
    * Variable items (1)

      * Application Context Item (1)

        * Item type (1, fixed value, ``0x10``)
        * Item length (1)
        * Application Context Name (1, fixed in an application)
      * Presentation Context Item(s) (1 or more)

        * Item type (1, fixed value, ``0x21``)
        * Item length (1)
        * Context ID (1)
        * Abstract/Transfer Syntax Sub-items (1)

          * Abstract Syntax Sub-item (1)

            * Item type (1, fixed, ``0x30``)
            * Item length (1)
            * Abstract syntax name (1)
          * Transfer Syntax Sub-items (1 or more)

            * Item type (1, fixed, ``0x40``)
            * Item length (1)
            * Transfer syntax name(s) (1 or more)
      * User Information Item (1)

        * Item type (1, fixed, ``0x50``)
        * Item length (1)
        * User data Sub-items (2 or more)

            * Maximum Length Received Sub-item (1)
            * Implementation Class UID Sub-item (1)
            * Optional User Data Sub-items (0 or more)

    **Encoding**

    When encoded, an A-ASSOCIATE-RQ PDU has the following structure, taken
    from `Table 9-11<part08/sect_9.3.2.html>` (offsets shown with Python
    indexing). PDUs are always encoded using Big Endian.

    +--------+-------------+------------------+
    | Offset | Length      | Description      |
    +========+=============+==================+
    | 0      | 1           | PDU type         |
    +--------+-------------+------------------+
    | 1      | 1           | Reserved         |
    +--------+-------------+------------------+
    | 2      | 4           | PDU length       |
    +--------+-------------+------------------+
    | 6      | 2           | Protocol version |
    +--------+-------------+------------------+
    | 8      | 2           | Reserved         |
    +--------+-------------+------------------+
    | 10     | 16          | Called AE title  |
    +--------+-------------+------------------+
    | 26     | 16          | Calling AE title |
    +--------+-------------+------------------+
    | 42     | 32          | Reserved         |
    +--------+-------------+------------------+
    | 74     | Variable    | Variable items   |
    +--------+-------------+------------------+

    References
    ----------
    * DICOM Standard, Part 8, Sections :dcm:`9.3.2<part08/sect_9.3.2.html>`
      and :dcm:`9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_ASSOCIATE | None = ...) -> None:
        """Initialise a new A-ASSOCIATE-RQ PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_ASSOCIATE
            The primitive to use to initialise the PDU.
        """
        ...

    def from_primitive(self, primitive: A_ASSOCIATE) -> None:
        """Set up the current PDU using an A-ASSOCIATE (request) primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_ASSOCIATE
            The primitive to use to set the current PDU field values.
        """
        ...

    def to_primitive(self) -> A_ASSOCIATE:
        """Return an A-ASSOCIATE (request) primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_ASSOCIATE
            The primitive representation of the current PDU.
        """
        ...

    @property
    def application_context_name(self) -> UID | None:
        """Return the *Application Context Name*, if available.

        Returns
        -------
        pydicom.uid.UID or None
            The requestor's *Application Context Name* or None if not
            available.
        """
        ...

    @property
    def called_ae_title(self) -> str:
        """Get or set the *Called AE Title* field value as :class:`str`.

        Will be converted to a fixed length 16-byte value (padded with trailing
        spaces ``0x20``). Leading and trailing spaces are non-significant and a
        value of 16 spaces is not allowed.

        Parameters
        ----------
        value : str or bytes
            The value you wish to set. A value consisting of spaces is not
            allowed and values longer than 16 characters will be truncated.
        """
        ...

    @called_ae_title.setter
    def called_ae_title(self, value: str | bytes) -> None:
        """Set the *Called AE Title* field value."""
        ...

    @property
    def calling_ae_title(self) -> str:
        """Return the *Calling AE Title* field value as :class:`str`."""
        ...

    @calling_ae_title.setter
    def calling_ae_title(self, value: str | bytes) -> None:
        """Set the *Calling AE Title* field value.

        Will be converted to a fixed length 16-byte value (padded with trailing
        spaces ``0x20``). Leading and trailing spaces are non-significant and a
        value of 16 spaces is not allowed.

        Parameters
        ----------
        value : str or bytes
            The value you wish to set. A value consisting of spaces is not
            allowed and values longer than 16 characters will be truncated.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as :class:`int`."""
        ...

    @property
    def presentation_context(self) -> list[PresentationContextItemRQ]:
        """Return a list of the Presentation Context items.

        Returns
        -------
        list of pdu_items.PresentationContextItemRQ
            The Presentation Context items.
        """
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

    @property
    def user_information(self) -> UserInformationItem | None:
        """Return the User Information Item, if available.

        Returns
        -------
        pdu_items.UserInformationItem or None
            The requestor's User Information object or ``None``, if not
            available.
        """
        ...

class A_ASSOCIATE_AC(PDU):
    """An A-ASSOCIATE-AC PDU.

    An A-ASSOCIATE-AC PDU is sent by an association acceptor to indicate that
    association negotiation has been successful.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x02``).
    protocol_version : int
        The *Protocol Version* field value (default ``0x01``).
    variable_items : list
        A list containing the A-ASSOCIATE-AC's 'Variable Items'. Contains
        one Application Context item, one or more Presentation Context items
        and one User Information item. The order of the items is not
        guaranteed.

    Notes
    -----
    An A-ASSOCIATE-AC PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x02``)
    * PDU length (1)
    * Protocol version (1, default value, ``0x01``)
    * Variable items (1)

      * Application Context Item (1)

        * Item type (1, fixed value, ``0x10``)
        * Item length (1)
        * Application Context Name (1, fixed in an application)
      * Presentation Context Item(s) (1 or more)

        * Item type (1, fixed value, ``0x21``)
        * Item length (1)
        * Context ID (1)
        * Result/reason (1)
        * Transfer Syntax Sub-items (1)

          * Item type (1, fixed, ``0x40``)
          * Item length (1)
          * Transfer syntax name(s) (1)
      * User Information Item (1)

        * Item type (1, fixed, ``0x50``)
        * Item length (1)
        * User data Sub-items (2 or more)

            * Maximum Length Received Sub-item (1)
            * Implementation Class UID Sub-item (1)
            * Optional User Data Sub-items (0 or more)

    **Encoding**

    When encoded, an A-ASSOCIATE-AC PDU has the following structure, taken
    from Table 9-17 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+------------------+
    | Offset | Length      | Description      |
    +========+=============+==================+
    | 0      | 1           | PDU type         |
    +--------+-------------+------------------+
    | 1      | 1           | Reserved         |
    +--------+-------------+------------------+
    | 2      | 4           | PDU length       |
    +--------+-------------+------------------+
    | 6      | 2           | Protocol version |
    +--------+-------------+------------------+
    | 8      | 2           | Reserved         |
    +--------+-------------+------------------+
    | 10     | 16          | Reserved^        |
    +--------+-------------+------------------+
    | 26     | 16          | Reserved^        |
    +--------+-------------+------------------+
    | 42     | 32          | Reserved         |
    +--------+-------------+------------------+
    | 74     | Variable    | Variable items   |
    +--------+-------------+------------------+

    ^ The reserved fields shall be sent with a value identical to the value
    received in the A-ASSOCIATE-RQ but their values shall not be tested.

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.3 <part08/sect_9.3.3.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_ASSOCIATE | None = ...) -> None:
        """Initialise a new A-ASSOCIATE-AC PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_ASSOCIATE
            The primitive to use to initialise the PDU.
        """
        ...

    def from_primitive(self, primitive: A_ASSOCIATE) -> None:
        """Set up the current PDU using an A-ASSOCIATE (accept) primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_ASSOCIATE
            The primitive to use to set the current PDU field values.
        """
        ...

    def to_primitive(self) -> A_ASSOCIATE:
        """Return an A-ASSOCIATE (accept) primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_ASSOCIATE
            The primitive representation of the current PDU.
        """
        ...

    @property
    def application_context_name(self) -> UID | None:
        """Return the *Application Context Name*, if available.

        Returns
        -------
        pydicom.uid.UID or None
            The acceptor's *Application Context Name* or None if not available.
        """
        ...

    @property
    def called_ae_title(self) -> str:
        """Return the value sent in the *Called AE Title* reserved space.

        While the standard says this value should match the A-ASSOCIATE-RQ
        value there is no guarantee and this should not be used as a check
        value.

        Returns
        -------
        str
            The value the A-ASSOCIATE-AC sent in the *Called AE Title* reserved
            space. May be an empty string if unable to decode the value.
        """
        ...

    @property
    def calling_ae_title(self) -> str:
        """Return the value sent in the *Calling AE Title* reserved space.

        While the standard says this value should match the A-ASSOCIATE-RQ
        value there is no guarantee and this should not be used as a check
        value.

        Returns
        -------
        bytes
            The value the A-ASSOCIATE-AC sent in the *Calling AE Title*
            reserved space. May be an empty string if unable to decode the
            value.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    @property
    def presentation_context(self) -> list[PresentationContextItemAC]:
        """Return a list of the Presentation Context Items.

        Returns
        -------
        list of pdu_items.PresentationContextItemAC
            The Presentation Context Items.
        """
        ...

    @property
    def reserved_aec(self) -> str:
        """Get or set the A-ASSOCIATE-AC's reserved *Calling AE Title* value.

        Parameters
        ----------
        value : str or bytes
            The value at offset 27-42 in the A-ASSOCIATE-AC PDU, usually the
            same value as the *Calling AE Title*.

        Returns
        -------
        str
            The decoded value at offset 27-42 in the A-ASSOCIATE-AC PDU,
            usually the same value as the *Calling AE Title*, or ``''`` if
            unable to decode the value.
        """
        ...

    @reserved_aec.setter
    def reserved_aec(self, value: str | bytes) -> None:
        """Set the A-ASSOCIATE-AC's *Calling AE Title* value."""
        ...

    @property
    def reserved_aet(self) -> str:
        """Get or set the A-ASSOCIATE-AC's reserved *Called AE Title* value.

        Parameters
        ----------
        value : str or bytes
            The value at offset 11-26 in the A-ASSOCIATE-AC PDU, usually the
            same value as the *Called AE Title*.

        Returns
        -------
        str
            The decoded value at offset 11-26 in the A-ASSOCIATE-AC PDU,
            usually the same value as the *Called AE Title*, or ``''`` if
            unable to decode the value.
        """
        ...

    @reserved_aet.setter
    def reserved_aet(self, value: str | bytes) -> None:
        """Set the A-ASSOCIATE-AC's *Called AE Title* value."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

    @property
    def user_information(self) -> UserInformationItem | None:
        """Return the User Information Item, if available.

        Returns
        -------
        pdu_items.UserInformationItem or None
            The acceptor's User Information object or None, if not available.
        """
        ...

class A_ASSOCIATE_RJ(PDU):
    """An A-ASSOCIATE-RJ PDU.

    An A-ASSOCIATE-RJ PDU is sent by an association acceptor to indicate that
    association negotiation has been unsuccessful.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x03``).
    reason_diagnostic : int
        The *Reason/Diagnostic* field value.
    result : int
        The *Result* field value.
    source : int
        The *Source* field value.

    Notes
    -----
    An A-ASSOCIATE-RJ PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x03``)
    * PDU length (1)
    * Result (1)
    * Source (1)
    * Reason/Diagnostic (1)

    **Encoding**

    When encoded, an A-ASSOCIATE-RJ PDU has the following structure, taken
    from Table 9-21 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+-------------------+
    | Offset | Length      | Description       |
    +========+=============+===================+
    | 0      | 1           | PDU type          |
    +--------+-------------+-------------------+
    | 1      | 1           | Reserved          |
    +--------+-------------+-------------------+
    | 2      | 4           | PDU length        |
    +--------+-------------+-------------------+
    | 6      | 1           | Reserved          |
    +--------+-------------+-------------------+
    | 7      | 1           | Result            |
    +--------+-------------+-------------------+
    | 8      | 1           | Source            |
    +--------+-------------+-------------------+
    | 9      | 1           | Reason/diagnostic |
    +--------+-------------+-------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.4 <part08/sect_9.3.4.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_ASSOCIATE | None = ...) -> None:
        """Initialise a new A-ASSOCIATE-RJ PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_ASSOCIATE
            The primitive to use to initialise the PDU.
        """
        ...

    def from_primitive(self, primitive: A_ASSOCIATE) -> None:
        """Set up the current PDU using an A-ASSOCIATE (reject) primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_ASSOCIATE
            The primitive to use to set the current PDU field values.
        """
        ...

    def to_primitive(self) -> A_ASSOCIATE:
        """Return an A-ASSOCIATE (reject) primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_ASSOCIATE
            The primitive representation of the current PDU.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    @property
    def reason_str(self) -> str:
        """Return a str describing the *Reason/Diagnostic* field value."""
        ...

    @property
    def result_str(self) -> str:
        """Return a str describing the *Result* field value."""
        ...

    @property
    def source_str(self) -> str:
        """Return a str describing the *Source* field value."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

class P_DATA_TF(PDU):
    """A P-DATA-TF PDU.

    A P-DATA-TF PDU is used once an association has been established to send
    DIMSE message data.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x04``).
    presentation_data_value_items : list of pdu.PresentationDataValueItem
        The *Presentation Data Value Item(s)* field value.

    Notes
    -----
    A P-DATA-TF PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x04``)
    * PDU length (1)
    * Presentation data value Item(s) (1 or more)

    **Encoding**

    When encoded, a P-DATA-TF PDU has the following structure, taken
    from Table 9-22 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+-------------------------------+
    | Offset | Length      | Description                   |
    +========+=============+===============================+
    | 0      | 1           | PDU type                      |
    +--------+-------------+-------------------------------+
    | 1      | 1           | Reserved                      |
    +--------+-------------+-------------------------------+
    | 2      | 4           | PDU length                    |
    +--------+-------------+-------------------------------+
    | 6      | Variable    | Presentation data value items |
    +--------+-------------+-------------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.5 <part08/sect_9.3.5.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: P_DATA | None = ...) -> None:
        """Initialise a new P-DATA-TF PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.P_DATA
            The primitive to use to initialise the PDU.
        """
        ...

    def from_primitive(self, primitive: P_DATA) -> None:
        """Set up the current PDU using a P-DATA primitive.

        Parameters
        ----------
        primitive : pdu_primitives.P_DATA
            The primitive to use to set the current PDU field values.
        """
        ...

    def to_primitive(self) -> P_DATA:
        """Return a P-DATA primitive from the current PDU.

        Returns
        -------
        pdu_primitives.P_DATA
            The primitive representation of the current PDU.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

class A_RELEASE_RQ(PDU):
    """An A-RELEASE-RQ PDU.

    An A-RELEASE-RQ PDU is used once an association has been established to
    initiate the release of the association.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x05``).

    Notes
    -----
    An A-RELEASE-RQ PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x05``)
    * PDU length (1, fixed value, 4)

    **Encoding**

    When encoded, an A-RELEASE-RQ PDU has the following structure, taken
    from Table 9-24 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+---------------+
    | Offset | Length      | Description   |
    +========+=============+===============+
    | 0      | 1           | PDU type      |
    +--------+-------------+---------------+
    | 1      | 1           | Reserved      |
    +--------+-------------+---------------+
    | 2      | 4           | PDU length    |
    +--------+-------------+---------------+
    | 6      | 4           | Reserved      |
    +--------+-------------+---------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.6 <part08/sect_9.3.6.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_RELEASE | None = ...) -> None:
        """Initialise a new A-RELEASE-RQ PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_RELEASE
            The primitive to use to initialise the PDU.
        """
        ...

    @staticmethod
    def from_primitive(primitive: A_RELEASE) -> None:
        """Set up the current PDU using an A-RELEASE (request) primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_RELEASE
            The primitive to use to set the current PDU field values.
        """
        ...

    @staticmethod
    def to_primitive() -> A_RELEASE:
        """Return an A-RELEASE (request) primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_RELEASE
            The primitive representation of the current PDU.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

class A_RELEASE_RP(PDU):
    """An A-RELEASE-RP PDU.

    An A-RELEASE-RP PDU is used once an association has been established to
    confirm the release of the association.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x06``).

    Notes
    -----
    An A-RELEASE-RP PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x06``)
    * PDU length (1, fixed value, ``0x00000004``)

    **Encoding**

    When encoded, an A-RELEASE-RP PDU has the following structure, taken
    from Table 9-25 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+---------------+
    | Offset | Length      | Description   |
    +========+=============+===============+
    | 0      | 1           | PDU type      |
    +--------+-------------+---------------+
    | 1      | 1           | Reserved      |
    +--------+-------------+---------------+
    | 2      | 4           | PDU length    |
    +--------+-------------+---------------+
    | 6      | 4           | Reserved      |
    +--------+-------------+---------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.7 <part08/sect_9.3.7.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_RELEASE | None = ...) -> None:
        """Initialise a new A-RELEASE-RP PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_RELEASE
            The primitive to use to initialise the PDU.
        """
        ...

    @staticmethod
    def from_primitive(primitive: A_RELEASE) -> None:
        """Set up the current PDU using an A-release (response) primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_RELEASE
            The primitive to use to set the current PDU field values.
        """
        ...

    @staticmethod
    def to_primitive() -> A_RELEASE:
        """Return an A-RELEASE (response) primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_RELEASE
            The primitive representation of the current PDU.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

class A_ABORT_RQ(PDU):
    """An A-ABORT-RQ PDU.

    An A-ABORT-RQ PDU is used to abort the association.

    Attributes
    ----------
    pdu_type : int
        The *PDU Type* field value (``0x07``).
    reason_diagnostic : int
        The *Reason/Diagnostic* field value.
    source : int
        The *Source* field value.

    Notes
    -----
    An A-ABORT-RQ PDU requires the following parameters:

    * PDU type (1, fixed value, ``0x06``)
    * PDU length (1, fixed value, 4)
    * Source (1)
    * Reason/Diagnostic (1)

    **Encoding**

    When encoded, an A-ABORT-RQ PDU has the following structure, taken
    from Table 9-26 (offsets shown with Python indexing). PDUs are always
    encoded using Big Endian.

    +--------+-------------+-------------------+
    | Offset | Length      | Description       |
    +========+=============+===================+
    | 0      | 1           | PDU type          |
    +--------+-------------+-------------------+
    | 1      | 1           | Reserved          |
    +--------+-------------+-------------------+
    | 2      | 4           | PDU length        |
    +--------+-------------+-------------------+
    | 6      | 1           | Reserved          |
    +--------+-------------+-------------------+
    | 7      | 1           | Reserved          |
    +--------+-------------+-------------------+
    | 8      | 1           | Source            |
    +--------+-------------+-------------------+
    | 9      | 1           | Reason/Diagnostic |
    +--------+-------------+-------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.8 <part08/sect_9.3.8.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self, primitive: A_ABORT | A_P_ABORT | None = ...) -> None:
        """Initialise a new A-ABORT-RQ PDU.

        Parameters
        ----------
        primitive : pynetdicom.pdu_primitive.A_ABORT
            The primitive to use to initialise the PDU.
        """
        ...

    def from_primitive(self, primitive: _AbortType) -> None:
        """Set up the current PDU using an A-ABORT or A-P-ABORT primitive.

        Parameters
        ----------
        primitive : pdu_primitives.A_ABORT or pdu_primitives.A_P_ABORT
            The primitive to use to set the current PDU field values.
        """
        ...

    def to_primitive(self) -> _AbortType:
        """Return an A-ABORT or A-P-ABORT primitive from the current PDU.

        Returns
        -------
        pdu_primitives.A_ABORT or pdu_primitives.A_P_ABORT
            The primitive representation of the current PDU.
        """
        ...

    @property
    def pdu_length(self) -> int:
        """Return the *PDU Length* field value as an int."""
        ...

    def __str__(self) -> str:
        """Return a string representation of the PDU."""
        ...

    @property
    def source_str(self) -> str:
        """Return a str description of the *Source* field value."""
        ...

    @property
    def reason_str(self) -> str:
        """Return a str description of the *Reason/Diagnostic* field value."""
        ...

_AbortType = A_ABORT | A_P_ABORT
_PDUType = A_ASSOCIATE_RQ | A_ASSOCIATE_AC | A_ASSOCIATE_RJ | P_DATA_TF | A_RELEASE_RQ | A_RELEASE_RP | A_ABORT_RQ

PDU_TYPES = ...
