"""This type stub file was generated by pyright."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from pydicom.uid import UID
from pynetdicom._globals import OptionalUIDType
from pynetdicom.pdu_primitives import (
    AsynchronousOperationsWindowNegotiation,
    ImplementationClassUIDNotification,
    ImplementationVersionNameNotification,
    MaximumLengthNotification,
    SCP_SCU_RoleSelectionNegotiation,
    SOPClassCommonExtendedNegotiation,
    SOPClassExtendedNegotiation,
    UserIdentityNegotiation,
    _UserInformationPrimitiveType,  # pyright: ignore[reportPrivateUsage]
)
from pynetdicom.presentation import PresentationContext

__all__ = [
    'AbstractSyntaxSubItem',
    'ApplicationContextItem',
    'MaximumLengthSubItem',
    'PDUItem',
    'PresentationContextItemAC',
    'PresentationContextItemRQ',
    'SOPClassCommonExtendedNegotiation',
    'SOPClassExtendedNegotiation',
    'TransferSyntaxSubItem',
    'UserIdentityNegotiation',
    'UserInformationItem',
]

LOGGER = ...
UCHAR = ...
UINT2 = ...
UINT4 = ...
UNPACK_UCHAR = ...
UNPACK_UINT2 = ...
UNPACK_UINT4 = ...
PACK_UCHAR = ...
PACK_UINT2 = ...
PACK_UINT4 = ...
_DecoderType = list[tuple[int, int | None, str, Callable[[Any], bytes], list[Any]]]
_EncoderType = list[tuple[str, Callable[[Any], bytes], list[Any]]]
_PDUItemType = list[
    ApplicationContextItem | PresentationContextItemRQ | PresentationContextItemAC | UserInformationItem
]

class PDUItem:
    """Base class for PDU Items and Sub-items.

    See Also
    --------
    pdu.PDU
    """

    def decode(self, bytestream: bytes) -> None:
        """Decode `bytestream` and use the result to set the field values of the PDU item.

        Parameters
        ----------
        bytestream : bytes
            The PDU data to be decoded.
        """

    def encode(self) -> bytes:
        """Return the encoded PDU as bytes.

        Returns
        -------
        bytes
            The encoded PDU.
        """

    def __eq__(self, other: Any) -> bool:
        """Return True if `self` equals `other`."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def item_type(self) -> int:
        """Return the item's *Item Type* field value as :class:`int`."""

    def __len__(self) -> int:
        """Return the total length of the encoded item as :class:`int`."""

    def __ne__(self, other: Any) -> bool:
        """Return True if `self` does not equal `other`."""

class ApplicationContextItem(PDUItem):
    """An Application Context Item.

    An Application Context explicitly defines the set of application service
    elements, related options and any other information necessary for the
    inter-working of Application Entities on an association.

    Notes
    -----
    An Application Context Item requires the following parameters:

       * Item type (1, fixed value, ``0x10``)
       * Item length (1)
       * Application Context Name (1)

    **Application Context Names**

    Application Context Names are OSI Object Identifiers in a numeric form as
    defined by `ISO/IEC 8824-1:2015
    <https://www.iso.org/standard/68350.html>`_.
    They are encoded as an ISO 646:1990-Basic G0 Set
    Numeric String of bytes (characters 0-9), separated by the character
    ``.`` (``0x2e``). No separator or padding shall be present before the
    first digit of the first component or after the last digit of the last
    component.

    Application context names shall not exceed 64 total characters.

    A single DICOM Application Context Name is defined for the current
    version of the DICOM Standard and it is *1.2.840.10008.3.1.1.1*.

    **Encoding**

    When encoded, an Application Context Item has the following structure,
    taken from Part 7, Table 9-12 of the DICOM Standard (offsets shown with
    Python indexing). Items are always encoded using Big Endian. Encoding of
    the Application Context Name parameter follows the rules in Part 8,
    :dcm:`Annex F<part08/chapter_F.html>`

    +--------+-------------+--------------------------+
    | Offset | Length      | Description              |
    +========+=============+==========================+
    | 0      | 1           | Item type                |
    +--------+-------------+--------------------------+
    | 1      | 1           | Reserved                 |
    +--------+-------------+--------------------------+
    | 2      | 2           | Item length              |
    +--------+-------------+--------------------------+
    | 4      | Variable    | Application context name |
    +--------+-------------+--------------------------+

    References
    ----------
    * DICOM Standard, Part 7, :dcm:`Annex A<part07/chapter_A.html>`
    * DICOM Standard, Part 8, :dcm:`Annex F<part08/chapter_F.html>`
    * DICOM Standard, Part 7,
      :dcm:`Annex A.2.1<part07/sect_A.2.html#sect_A.2.1>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.2.1<part08/sect_9.3.2.html#sect_9.3.2.1>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Application Context Item."""

    @property
    def application_context_name(self) -> UID:
        """Return the item's *Application Context Name* field value as `pydicom.uid.UID`."""

    @application_context_name.setter
    def application_context_name(self, value: str | bytes | UID) -> None:
        """Set the *Application Context Name* field value.

        Parameters
        ----------
        value : pydicom.uid.UID, str or bytes
            The value of the Application Context Name's UID
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class PresentationContextItemRQ(PDUItem):
    """A Presentation Context (RQ) Item.

    Presentation Contexts (RQ) Items are used by the association requestor to
    propose Abstract Syntaxes (specifications of data elements with associated
    semantics) and Transfer Syntaxes (sets of encoding rules).

    Notes
    -----
    A Presentation Context (RQ) Item requires the following parameters:

       * Item type (1, fixed value, ``0x20``)
       * Item length (1)
       * Presentation context ID (1)
       * Abstract/Transfer Syntax Sub-items (1)

         * Abstract Syntax Sub-item (1)

           * Item type (1, fixed, ``0x30``)
           * Item length (1)
           * Abstract syntax name (1)
         * Transfer Syntax Sub-items (1 or more)

           * Item type (1, fixed, ``0x40``)
           * Item length (1)
           * Transfer syntax name(s) (1 or more)

    **Encoding**

    When encoded, a Presentation Context (RQ) Item has the following structure,
    taken from Part 8, Table 9-13 of the DICOM Standard (offsets shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | 1           | Presentation context ID            |
    +--------+-------------+------------------------------------+
    | 5      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 6      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 7      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 8      | Variable    | Abstract/transfer syntax sub-items |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8, :dcm:`Annex B <part08/chapter_B.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.2.2 <part08/sect_9.3.2.2.2.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1 <part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Presentation Context (RQ) Item."""

    def from_primitive(self, primitive: PresentationContext) -> None:
        """Set the item's values using a Presentation Context primitive.

        Parameters
        ----------
        primitive : presentation.PresentationContext
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> PresentationContext:
        """Return a PresentationContext primitive from the current Item.

        Returns
        -------
        presentation.PresentationContext
            The primitive representation of the current Item.
        """

    @property
    def abstract_syntax(self) -> UID | None:
        """Return the *Abstract Syntax*, if available.

        Returns
        -------
        pydicom.uid.UID or None
        """

    @property
    def context_id(self) -> int | None:
        """Return the item's *Presentation Context ID* field value as :class:`int`."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def transfer_syntax(self) -> list[UID]:
        """Return the *Transfer Syntax(es)*.

        Returns
        -------
        list of pydicom.uid.UID
        """

class PresentationContextItemAC(PDUItem):
    """A Presentation Context (AC) item.

    Presentation Contexts (AC) Items are used by the association acceptor to
    signal which Abstract Syntaxes and Transfer Syntaxes have been accepted or
    rejected.

    Notes
    -----
    A Presentation Context (AC) Item requires the following parameters:

       * Item type (1, fixed value, ``0x21``)
       * Item length (1)
       * Presentation context ID (1)
       * Result/reason (1)
       * Transfer Syntax Sub-item (1)

         * Item type (1, fixed, 0x40)
         * Item length (1)
         * Transfer syntax name (1)

    **Encoding**

    When encoded, a Presentation Context (AC) Item has the following structure,
    taken from Part 8, Table 9-13 of the DICOM Standard (offsets shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | 1           | Presentation context ID            |
    +--------+-------------+------------------------------------+
    | 5      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 6      | 1           | Result/reason                      |
    +--------+-------------+------------------------------------+
    | 7      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 8      | Variable    | Transfer syntax sub-item           |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8, :dcm:`Section 9.3.3.2<part08/sect_9.3.3.2.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Presentation Context (AC) Item."""

    def from_primitive(self, primitive: PresentationContext) -> None:
        """Set the item's values using a Presentation Context primitive.

        Parameters
        ----------
        primitive : presentation.PresentationContext
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> PresentationContext:
        """Return a PresentationContext primitive from the current Item.

        Returns
        -------
        presentation.PresentationContext
            The primitive representation of the current Item.
        """

    @property
    def context_id(self) -> int | None:
        """Return the item's *Presentation Context ID* field value."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def result(self) -> int | None:
        """Return the item's *Result/reason* field value."""

    @property
    def result_str(self) -> str:
        """Get a string describing the result."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def transfer_syntax(self) -> UID | None:
        """Return the *Transfer Syntax*, if available.

        Returns
        -------
        pydicom.uid.UID or None
            If no Transfer Syntax Sub-item or an empty Transfer Syntax Sub-item
            has been sent by the Acceptor then returns None, otherwise returns
            the Transfer Syntax Sub-item's transfer syntax UID.
        """

class UserInformationItem(PDUItem):
    """A User Information Item.

    Used by the association requestor and acceptor to include user information
    in the association negotiation.

    Notes
    -----
    A User Information Item requires the following parameters:

    * Item type (1, fixed, ``0x50``)
    * Item length (1)
    * User data sub-items (2 or more)

     * Maximum Length Received Sub-item (1)
     * Implementation Class UID Sub-item (1)
     * Optional User Data Sub-items (0 or more)

    **Encoding**

    When encoded, a User Information Item has the following structure,
    taken from Part 8, Table 9-16 of the DICOM Standard (offsets shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | Variable    | User data                          |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.2.3<part08/sect_9.3.2.3.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`

    """

    def __init__(self) -> None:
        """Initialise a new User Information Item."""

    def from_primitive(self, primitive: _UserInformationPrimitiveType) -> None:
        """Set up the current Item using User Information primitives.

        Parameters
        ----------
        primitive : list of User Information primitives
            Must contain:

            - MaximumLengthNotification
            - ImplementationClassUIDNotification

            May optionally contain one or more:

            - ImplementationVersionNameNotification
            - AsynchronousOperationsWindowNegotiation
            - SCP_SCU_RoleSelectionNegotiation
            - SOPClassExtendedNegotiation
            - SOPClassCommonExtendedNegotiation
            - UserIdentityNegotiation
        """

    def to_primitive(self) -> _UserInformationPrimitiveType:
        """Return a list of User Information primitives from the current Item.

        Returns
        -------
        list of User Information primitives
            Must contain:

            - MaximumLengthNotification
            - ImplementationClassUIDNotification

            May optionally contain one or more:

            - ImplementationVersionNameNotification
            - AsynchronousOperationsWindowNegotiation
            - SCP_SCU_RoleSelectionNegotiation
            - SOPClassExtendedNegotiation
            - SOPClassCommonExtendedNegotiation
            - UserIdentityNegotiation
        """

    @property
    def async_ops_window(self) -> AsynchronousOperationsWindowSubItem | None:
        """Return the *Asynchronous Operations Window Sub-item*, if available."""

    @property
    def common_ext_neg(self) -> list[SOPClassCommonExtendedNegotiationSubItem]:
        """Return the *SOP Class Common Extended Negotiation Sub-items*."""

    @property
    def ext_neg(self) -> list[SOPClassExtendedNegotiationSubItem]:
        """Return the *SOP Class Extended Negotiation Sub-items*."""

    @property
    def implementation_class_uid(self) -> UID | None:
        """Return the item's *Implementation Class UID* field value, if available."""

    @property
    def implementation_version_name(self) -> str | None:
        """Return the item's *Implementation Version Name* field value, if available."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def maximum_length(self) -> int | None:
        """Return the item's *Maximum Length Received* field value, if available."""

    @property
    def role_selection(self) -> dict[UID, SCP_SCU_RoleSelectionSubItem]:
        """Return the *SCP/SCU Role Selection Sub-items*.

        Returns
        -------
        dict
            The SCP/SCU Role Selection items as {item.uid : item}.
        """

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def user_identity(self) -> UserIdentitySubItemAC | UserIdentitySubItemRQ | None:
        """Return the *User Identity Sub-item*, if available."""

class AbstractSyntaxSubItem(PDUItem):
    """An Abstract Syntax Sub-item.

    An Abstract Syntax is the specification of data elements with associated
    semantics. In particular it allows communicating Application Entities to
    negotiate an agreed set of DICOM Data Elements and/or Information Object
    Class definitions.

    Notes
    -----
    An Abstract Syntax Sub-item requires the following parameters:

       * Item type (1, fixed value, ``0x30``)
       * Item length (1)
       * Abstract syntax name (1)

    **Abstract Syntax Names**

    Abstract Syntax Names are OSI Object Identifiers in a numeric form as
    defined by ISO 8824. They may be either DICOM registered or privately
    defined. They're encoded as an ISO 646:1990-Basic G0 Set Numeric String of
    bytes (characters 0-9), separated by the character ``.`` (``0x2e``) and
    shall not exceed 64 total characters. No separator or padding shall be
    present before the first digit of the first component or after the last
    digit of the last component.

    **Encoding**

    When encoded, an Abstract Syntax Item has the following structure,
    taken from Part 8, Table 9-14 of the DICOM Standard (offsets shown with
    Python indexing). Items are
    always encoded using Big Endian. Encoding of the Abstract Syntax Name
    parameter follows the rules in Part 8,
    :dcm:`Annex F <part08/chapter_F.html>`.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | Variable    | Abstract syntax name               |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Annex B <part08/chapter_B.html>`
    * `ISO/IEC 8824-1:2015 <https://www.iso.org/standard/68350.html>`_
    * DICOM Standard, Part 8,
      :dcm:`Annex F <part08/chapter_F.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.2.2.1 <part08/sect_9.3.2.2.html#sect_9.3.2.2.1>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Abstract Syntax Item."""

    @property
    def abstract_syntax(self) -> UID | None:
        """Return the item's *Abstract Syntax Name* field value."""

    @property
    def abstract_syntax_name(self) -> UID | None:
        """Return the item's *Abstract Syntax Name* field value."""

    @abstract_syntax_name.setter
    def abstract_syntax_name(self, value: OptionalUIDType) -> None:
        """Set the *Abstract Syntax Name* field value.

        Parameters
        ----------
        value : pydicom.uid.UID, bytes or str
            The value for the Abstract Syntax Name.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class TransferSyntaxSubItem(PDUItem):
    """A Transfer Syntax Sub-item.

    A Transfer Syntax is a set of encoding rules able to unambiguously
    represent the data elements defined by one or more Abstract Syntaxes.
    In particular, it allows communicating Application Entities to agree on the
    encoding techniques they are able to support (e.g. byte ordering,
    compression, etc).

    Notes
    -----
    A Transfer Syntax Sub-item requires the following parameters:

       * Item type (1, fixed value, ``0x40``)
       * Item length (1)
       * Transfer syntax name (1 or more)

    **Transfer Syntax Names**

    Transfer Syntax Names are OSI Object Identifiers in a numeric form as
    defined by ISO 8824. They may be either DICOM registered or privately
    defined. They're encoded as an ISO 646:1990-Basic G0 Set Numeric String of
    bytes (characters 0-9), separated by the character ``.`` (``0x2e``) and
    shall not exceed 64 total characters. No separator or padding shall be
    present before the first digit of the first component or after the last
    digit of the last component.

    **Encoding**

    When encoded, a Transfer Syntax Item has the following structure,
    taken from Part 8, Table 9-15 of the DICOM Standard (offsets shown with
    Python indexing). Items are
    always encoded using Big Endian. Encoding of the Transfer Syntax Name
    parameter follows the rules in Part 8,
    :dcm:`Annex F <part08/chapter_F.html>`.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | Variable    | Transfer syntax name               |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Annex B <part08/chapter_B.html>`
    * `ISO/IEC 8824-1:2015 <https://www.iso.org/standard/68350.html>`_
    * DICOM Standard, Part 8,
      :dcm:`Annex F <part08/chapter_F.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.2.2.2 <part08/sect_9.3.2.2.2.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Abstract Syntax Item."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def transfer_syntax(self) -> UID | None:
        """Return the item's *Transfer Syntax Name* field value."""

    @property
    def transfer_syntax_name(self) -> UID | None:
        """Return the item's *Transfer Syntax Name* field value."""

    @transfer_syntax_name.setter
    def transfer_syntax_name(self, value: OptionalUIDType) -> None:
        """Set the *Transfer Syntax Name* field value.

        Parameters
        ----------
        value : pydicom.uid.UID, bytes or str
            The value for the Transfer Syntax Name
        """

class MaximumLengthSubItem(PDUItem):
    """A Maximum Length Sub-item.

    The Maximum Length Sub-item allows the receivers to limit the size of the
    Presentation Data Values List parameters of each P-DATA PDU.

    Notes
    -----
    A Maximum Length Sub-item requires the following parameters:

       * Item type (1, fixed, ``0x51``)
       * Item length (1)
       * Maximum length received (1)

    **Encoding**

    When encoded, a Maximum Length Sub-item has the following structure,
    taken from Table D.1-1 of the DICOM Standard (offsets shown with Python
    indexing). Items are
    always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | 4           | Maximum length received            |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Annex D.1 <part08/chapter_D.html#sect_D.1.1>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Maximum Length Item."""

    def from_primitive(self, primitive: MaximumLengthNotification) -> None:
        """Set the item's values using a Maximum Length `primitive`.

        Parameters
        ----------
        primitive : pdu_primitives.MaximumLengthNotification
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> MaximumLengthNotification:
        """Return a Maximum Length primitive from the current Item.

        Returns
        -------
        pdu_primitives.MaximumLengthNotification
            The primitive representation of the current Item.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class ImplementationClassUIDSubItem(PDUItem):
    """An Implementation Class UID Sub-item.

    The Implementation Class UID Sub-item allows communicating Application
    Entities to identify each other at Association establishment.

    Notes
    -----
    An Implementation Class UID Sub-item requires the following parameters:

       * Item type (1, fixed, ``0x52``)
       * Item length (1)
       * Implementation Class UID (1)

    **Encoding**

    When encoded, an Implementation Class UID Sub-item has the following
    structure, taken from Tables D.3-1 and D.3-2 (offsets shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | Variable    | Implementation class UID           |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.2 <part07/sect_D.3.3.2.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Implementation Class UID Item."""

    def from_primitive(self, primitive: ImplementationClassUIDNotification) -> None:
        """Set the item's values using an Implementation Identification primitive.

        Parameters
        ----------
        primitive : pdu_primitives.ImplementationClassUIDNotification
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> ImplementationClassUIDNotification:
        """Return an Implementation Identification primitive from the current Item.

        Returns
        -------
        pdu_primitives.ImplementationClassUIDNotification
            The primitive representation of the current Item.
        """

    @property
    def implementation_class_uid(self) -> UID | None:
        """Return the item's *Implementation Class UID* field value as UID."""

    @implementation_class_uid.setter
    def implementation_class_uid(self, value: OptionalUIDType) -> None:
        """Set the *Implementation Class UID* field value.

        Parameters
        ----------
        value : pydicom.uid.UID, bytes or str
            The value to set.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class ImplementationVersionNameSubItem(PDUItem):
    """An Implementation Version Name Sub-item.

    The Implementation Version Name Sub-item allows communicating Application
    Entities to identify each other at Association establishment.

    Notes
    -----
    The Implementation Class UID Sub Item requires the following parameters:

       * Item type (1, fixed, ``0x55``)
       * Item length (1)
       * Implementation version name (1)

    **Implementation Version Name**

    The Implementation Version Name shall be encoded as a string of 1 to 16
    ISO 646:1990 (basic G0 set) characters.

    **Encoding**

    When encoded, an Implementation Version Name Sub-item has the following
    structure, taken from Tables D.3-3 and D.3-4 of the DICOM Standard (offsets
    shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+------------------------------------+
    | Offset | Length      | Description                        |
    +========+=============+====================================+
    | 0      | 1           | Item type                          |
    +--------+-------------+------------------------------------+
    | 1      | 1           | Reserved                           |
    +--------+-------------+------------------------------------+
    | 2      | 2           | Item length                        |
    +--------+-------------+------------------------------------+
    | 4      | Variable    | Implementation version name        |
    +--------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.2 <part07/sect_D.3.3.2.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Implementation Version Name Item."""

    def from_primitive(self, primitive: ImplementationVersionNameNotification) -> None:
        """Set the item's values using an Implementation Identification primitive.

        Parameters
        ----------
        primitive : pdu_primitives.ImplementationVersionNameNotification
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> ImplementationVersionNameNotification:
        """Return an Implementation Identification primitive from the current Item.

        Returns
        -------
        pdu_primitives.ImplementationVersionNameNotification
            The primitive representation of the current Item.
        """

    @property
    def implementation_version_name(self) -> str | None:
        """Return the item's *Implementation Version Name* field value."""

    @implementation_version_name.setter
    def implementation_version_name(self, value: str | bytes | None) -> None:
        """Set the *Implementation Version Name* field value."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class AsynchronousOperationsWindowSubItem(PDUItem):
    """An Asynchronous Operations Window Sub-item.

    Represents the Asynchronous Operations Window Sub Item used in
    A-ASSOCIATE-RQ and A-ASSOCIATE-AC PDUs.

    Notes
    -----
    An Asynchronous Operations Window Sub-item requires the following
    parameters:

       * Item type (1, fixed, ``0x53``)
       * Item length (1)
       * Maximum number of operations invoked (1)
       * Maximum number of operations performed (1)

    **Encoding**

    When encoded, an Asynchronous Operations Window Sub-item has the following
    structure, taken from Tables D.3-7 and D.3-8 of the DICOM Standard (offsets
    shown with
    Python indexing). Items are always encoded using Big Endian.

    +--------+-------------+-------------------------------------+
    | Offset | Length      | Description                         |
    +========+=============+=====================================+
    | 0      | 1           | Item type                           |
    +--------+-------------+-------------------------------------+
    | 1      | 1           | Reserved                            |
    +--------+-------------+-------------------------------------+
    | 2      | 2           | Item length                         |
    +--------+-------------+-------------------------------------+
    | 4      | 2           | Maximum number operations invoked   |
    +--------+-------------+-------------------------------------+
    | 6      | 2           | Maximum number operations performed |
    +--------+-------------+-------------------------------------+

    References
    ----------
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.3 <part07/sect_D.3.3.3.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Asynchronous Operations Window Item."""

    def from_primitive(self, primitive: AsynchronousOperationsWindowNegotiation) -> None:
        """Set the item's values using an Asynchronous Operations Window primitive.

        Parameters
        ----------
        primitive : pdu_primitives.AsynchronousOperationsWindowNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> AsynchronousOperationsWindowNegotiation:
        """Return an Asynchronous Operations Window primitive from the current Item.

        Returns
        -------
        pdu_primitives.AsynchronousOperationsWindowNegotiation
            The primitive representation of the current Item.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def max_operations_invoked(self) -> int | None:
        """Return the item's *Maximum Number Operations Invoked* field value."""

    @property
    def max_operations_performed(self) -> int | None:
        """Return the item's *Maximum Number Operations Performed* field value."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class SCP_SCU_RoleSelectionSubItem(PDUItem):
    """An SCP/SCU Role Selection Sub-item.

    An SCU/SCU Role Selection Sub-item allows communicating Application
    Entities to negotiate the roles in which they will server for each SOP
    Class or Meta SOP Class supported on the association.

    Notes
    -----
    An SCP/SCU Role Selection Sub-item requires the following parameters:

       * Item type (1, fixed, ``0x51``)
       * Item length (1)
       * UID length (1)
       * SOP Class UID (1)
       * SCU role (1)
       * SCP role (1)

    **Encoding**

    When encoded, an SCP/SCU Role Section Sub-item has the following
    structure, taken from Tables D.3-9 and D.3-10 of the DICOM Standard
    (offsets shown with
    Python indexing). Items are always encoded using Big Endian.
    The SOP Class UID parameter is encoded as a UID as per the rules in
    Part 5, Section 9.1 (ie NO trailing padding null byte).

    +----------------+----------+------------------------------------+
    | Offset         | Length   | Description                        |
    +================+==========+====================================+
    | 0              | 1        | Item type                          |
    +----------------+----------+------------------------------------+
    | 1              | 1        | Reserved                           |
    +----------------+----------+------------------------------------+
    | 2              | 2        | Item length                        |
    +----------------+----------+------------------------------------+
    | 4              | 2        | UID length                         |
    +----------------+----------+------------------------------------+
    | 6              | Variable | SOP class UID                      |
    +----------------+----------+------------------------------------+
    | 6 + UID length | 1        | SCP role                           |
    +----------------+----------+------------------------------------+
    | 7 + UID length | 1        | SCU role                           |
    +----------------+----------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 5,
      :dcm:`Section 9.1<part05/chapter_9.html#sect_9.1>`
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.4 <part07/sect_D.3.3.4.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new SCP/SCU Role Selection Item."""

    def from_primitive(self, primitive: SCP_SCU_RoleSelectionNegotiation) -> None:
        """Set the item's values using an SCP/SCU Role Selection primitive.

        Parameters
        ----------
        primitive : pdu_primitives.SCP_SCU_RoleSelectionNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> SCP_SCU_RoleSelectionNegotiation:
        """Return an SCP/SCU Role Selection primitive from the current Item.

        Returns
        -------
        pdu_primitives.SCP_SCU_RoleSelectionNegotiation
            The primitive representation of the current Item.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def scu(self) -> int | None:
        """Return the item's *SCU Role* field value."""

    @property
    def scu_role(self) -> int | None:
        """Return the item's *SCU Role* field value."""

    @scu_role.setter
    def scu_role(self, value: int | None) -> None:
        """Set the *SCU Role* field value."""

    @property
    def scp(self) -> int | None:
        """Return the item's *SCP Role* field value."""

    @property
    def scp_role(self) -> int | None:
        """Return the item's *SCP Role* field value."""

    @scp_role.setter
    def scp_role(self, value: int | None) -> None:
        """Set the *SCP Role* field value."""

    @property
    def sop_class_uid(self) -> UID | None:
        """Return the item's *SOP Class UID* field value."""

    @sop_class_uid.setter
    def sop_class_uid(self, value: OptionalUIDType) -> None:
        """Set the SOP class uid."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def uid(self) -> UID | None:
        """Return the item's *SOP Class UID* field value."""

    @property
    def uid_length(self) -> int:
        """Return the *UID Length* parameter value."""

class SOPClassExtendedNegotiationSubItem(PDUItem):
    """A SOP Class Extended Negotiation Sub-item.

    A SOP Class Extended Negotiation Sub-item allows peer Application Entities
    to exchange application information defined by specific Service Class
    specifications.

    Notes
    -----
    A SOP Class Extended Negotiation Sub-item requires the following
    parameters:

       * Item type (1, fixed, ``0x56``)
       * Item length (1)
       * SOP Class UID length (1)
       * SOP Class UID (1)
       * Service class application information

    **Encoding**

    When encoded, a SOP Class Extended Negotiation Sub-item has the following
    structure, taken from Table D.3-11 (offsets shown with
    Python indexing). Items are always encoded using Big Endian.
    The SOP Class UID parameter is encoded as a UID as per the rules in
    Part 5, Section 9.1 (ie NO trailing padding null byte).


    +----------------+-------------+------------------------------------+
    | Offset         | Length      | Description                        |
    +================+=============+====================================+
    | 0              | 1           | Item type                          |
    +----------------+-------------+------------------------------------+
    | 1              | 1           | Reserved                           |
    +----------------+-------------+------------------------------------+
    | 2              | 2           | Item length                        |
    +----------------+-------------+------------------------------------+
    | 4              | 2           | SOP class UID length               |
    +----------------+-------------+------------------------------------+
    | 6              | Variable    | SOP class UID                      |
    +----------------+-------------+------------------------------------+
    | 6 + UID length | Variable    | Service class application info     |
    +----------------+-------------+------------------------------------+

    References
    ----------
    * DICOM Standard, Part 5,
      :dcm:`Section 9.1<part05/chapter_9.html#sect_9.1>`
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.5 <part07/sect_D.3.3.5.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new SOP Class Extended Negotiation Item."""

    def from_primitive(self, primitive: SOPClassExtendedNegotiation) -> None:
        """Set the item's values using a SOP Class Extended Negotiation primitive.

        Parameters
        ----------
        primitive : pdu_primitives.SOPClassExtendedNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> SOPClassExtendedNegotiation:
        """Return a SOP Class Extended Negotiation primitive from the current Item.

        Returns
        -------
        pdu_primitives.SOPClassExtendedNegotiation
            The primitive representation of the current Item.
        """

    @property
    def app_info(self) -> bytes | None:
        """Return the item's *Service Class Application Information* field value."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def sop_class_uid(self) -> UID | None:
        """Return the item's *SOP Class UID* field value."""

    @sop_class_uid.setter
    def sop_class_uid(self, value: OptionalUIDType) -> None:
        """Set the *SOP Class UID* field value."""

    @property
    def sop_class_uid_length(self) -> int:
        """Return the item's *SOP Class UID Length* field value."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

    @property
    def uid(self) -> UID | None:
        """Return the item's *SOP Class UID* field value."""

class SOPClassCommonExtendedNegotiationSubItem(PDUItem):
    """A SOP Class Common Extended Negotiation Sub-item.

    A SOP Class Common Extended Negotiation Sub-item allows Application
    Entities to exchange application information in a generic non-Service
    class specific form.

    Notes
    -----
    A SOP Class Common Extended Negotiation Sub-item requires the following
    parameters:

       * Item type (1, fixed, ``0x57``)
       * Sub-item version (1, fixed, ``0x00``)
       * Item length (1)
       * SOP class UID length (1)
       * SOP class UID (1)
       * Service class UID length (1)
       * Service class UID (1)
       * Related general SOP class identification length (1)
       * Related general SOP class identification sub fields (0 or more)

         * Related general SOP class UID length (1)
         * Related general SOP class UID (1)

    **Encoding**

    When encoded, a SOP Class Common Extended Negotiation Sub-item has the
    following structure, taken from Table D.3-12 (offsets shown
    with Python indexing). Items are always encoded using Big Endian.
    The SOP Class UID, Service Class UID and the UIDs in the Related General
    SOP Class Identification parameters are encoded as UIDs as per the rules in
    Part 5, Section 9.1 (ie NO trailing padding null byte).

    +----------------------+----------+-------------------------------------+
    | Offset               | Length   | Description                         |
    +======================+==========+=====================================+
    | 0                    | 1        | Item type                           |
    +----------------------+----------+-------------------------------------+
    | 1                    | 1        | Sub item version                    |
    +----------------------+----------+-------------------------------------+
    | 2                    | 2        | Item length                         |
    +----------------------+----------+-------------------------------------+
    | 4                    | 2        | SOP class UID length                |
    +----------------------+----------+-------------------------------------+
    | 6                    | Variable | SOP class UID                       |
    +----------------------+----------+-------------------------------------+
    | 6 + SOP UID length   | 2        | Service class UID length            |
    +----------------------+----------+-------------------------------------+
    | 8 + SOP UID length   | Variable | Service class UID                   |
    +----------------------+----------+-------------------------------------+
    | 8 + SOP UID length   | 2        | Related general SOP class ID length |
    | + Service UID length |          |                                     |
    +----------------------+----------+-------------------------------------+
    | 10 + SOP UID length  | Variable | Related general SOP class ID        |
    | + Service UID length |          |                                     |
    +----------------------+----------+-------------------------------------+

    The Related General SOP Class Identification field is made up of a number
    of sub-fields with the following structure, taken from Table D.3-13.

    +--------+-------------+--------------------------------------+
    | Offset | Length      | Description                          |
    +========+=============+======================================+
    | 0      | 2           | Related general SOP class UID length |
    +--------+-------------+--------------------------------------+
    | 2      | Variable    | Related general SOP class UID        |
    +--------+-------------+--------------------------------------+

    References
    ----------
    * DICOM Standard, Part 5,
      :dcm:`Section 9.1<part05/chapter_9.html#sect_9.1>`
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.6 <part07/sect_D.3.3.6.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Implementation Version Name Item."""

    def from_primitive(self, primitive: SOPClassCommonExtendedNegotiation) -> None:
        """Set the item's values using a SOP Class Common Extended Negotiation primitive.

        Parameters
        ----------
        primitive : pdu_primitives.SOPClassCommonExtendedNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> SOPClassCommonExtendedNegotiation:
        """Return an SOP Class Common Extended Negotiation primitive from the current Item.

        Returns
        -------
        pdu_primitives.SOPClassCommonExtendedNegotiation
            The primitive representation of the current Item.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def related_general_sop_class_identification(self) -> list[UID]:
        """Return the item's *Related General SOP Class Identification* field value."""

    @related_general_sop_class_identification.setter
    def related_general_sop_class_identification(self, value_list: list[bytes | str | UID]) -> None:
        """Set the *Related General SOP Class Identification* field value.

        Parameters
        ----------
        value_list : list of pydicom.uid.UID
            A list of UIDs.
        """

    @property
    def related_general_sop_class_identification_length(self) -> int:
        """Return the item's *Related General SOP Class Identification Length* field value."""

    @property
    def sop_class_uid(self) -> UID | None:
        """Return the item's *SOP Class UID* field value."""

    @sop_class_uid.setter
    def sop_class_uid(self, value: OptionalUIDType) -> None:
        """Set the *SOP Class UID* field value."""

    @property
    def sop_class_uid_length(self) -> int:
        """Return the item's *SOP Class UID Length* field value."""

    @property
    def service_class_uid(self) -> UID | None:
        """Return the item's *Service Class UID* field value."""

    @service_class_uid.setter
    def service_class_uid(self, value: OptionalUIDType) -> None:
        """Set the *Service Class UID* field value."""

    @property
    def service_class_uid_length(self) -> int:
        """Return the item's *Service Class UID Length* field value."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class UserIdentitySubItemRQ(PDUItem):
    """A User Identity (RQ) Sub-item.

    A User Identity (RQ) Sub-item is used to notify the association acceptor of
    the user identity of the requestor.

    Notes
    -----
    A User Identity (RQ) Sub-item requires the following parameters:

    * Item type (1, fixed, ``0x58``)
    * Item length (1)
    * User identity type (1)
    * Positive response requested (1)
    * Primary field length (1)
    * Primary field (1)
    * Secondary field length (1)
    * Secondary field (only if user identity type = 2)

    **Encoding**

    When encoded, a User Identity (RQ) Sub-item has the following
    structure, taken from Tables D.3-14 of the DICOM Standard (offsets shown
    with
    Python indexing). Items are always encoded using Big Endian.

    +---------------------------+----------+-----------------------------+
    | Offset                    | Length   | Description                 |
    +===========================+==========+=============================+
    | 0                         | 1        | Item type                   |
    +---------------------------+----------+-----------------------------+
    | 1                         | 1        | Reserved                    |
    +---------------------------+----------+-----------------------------+
    | 2                         | 2        | Item length                 |
    +---------------------------+----------+-----------------------------+
    | 4                         | 1        | User identity type          |
    +---------------------------+----------+-----------------------------+
    | 5                         | 1        | Positive response requested |
    +---------------------------+----------+-----------------------------+
    | 6                         | 2        | Primary field length        |
    +---------------------------+----------+-----------------------------+
    | 8                         | Variable | Primary field               |
    +---------------------------+----------+-----------------------------+
    | 8 + Primary field length  | 2        | Secondary field length      |
    +---------------------------+----------+-----------------------------+
    | 10 + Primary field length | Variable | Secondary field             |
    +---------------------------+----------+-----------------------------+

    References
    ----------
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.7 <part07/sect_D.3.3.7.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new User Identity (RQ) Item."""

    def from_primitive(self, primitive: UserIdentityNegotiation) -> None:
        """Set the item's values using an User Identity primitive.

        Parameters
        ----------
        primitive : pdu_primitives.UserIdentityNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> UserIdentityNegotiation:
        """Return an  User Identity primitive from the current Item.

        Returns
        -------
        pdu_primitives.UserIdentityNegotiation
            The primitive representation of the current Item.
        """

    @property
    def id_type(self) -> int | None:
        """Return the item's *User Identity Type* field value."""

    @property
    def id_type_str(self) -> str:
        """Return a string description of the *User Identity Type* field."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def primary(self) -> bytes | None:
        """Return the item's *Primary Field* field value as :class:`bytes`."""

    @property
    def primary_field_length(self) -> int:
        """Return the item's *Primary Field Length* field value."""

    @property
    def response_requested(self) -> bool | None:
        """Return the item's *Positive Response Requested* field value as :class:`bool`."""

    @property
    def secondary(self) -> bytes | None:
        """Return the item's *Secondary Field* field value."""

    @property
    def secondary_field_length(self) -> int:
        """Return the item's *Secondary Field Length* field value."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class UserIdentitySubItemAC(PDUItem):
    """A User Identity (AC) Sub-item.

    A User Identity (AC) Sub-item is used to response with the server identity
    to the association requestor.

    Notes
    -----
    A User Identity (RQ) Sub-item requires the following parameters:

    * Item type (1, fixed, ``0x59``)
    * Item length (1)
    * Server response length (1)
    * Server response (1)

    **Encoding**

    When encoded, a User Identity (AC) Sub-item has the following
    structure, taken from Tables D.3-15 of the DICOM Standard (offsets shown
    with
    Python indexing). Items are always encoded using Big Endian.

    +-----------+----------+-----------------------------+
    | Offset    | Length   | Description                 |
    +===========+==========+=============================+
    | 0         | 1        | Item type                   |
    +-----------+----------+-----------------------------+
    | 1         | 1        | Reserved                    |
    +-----------+----------+-----------------------------+
    | 2         | 2        | Item length                 |
    +-----------+----------+-----------------------------+
    | 4         | 2        | Server response length      |
    +-----------+----------+-----------------------------+
    | 6         | Variable | Server response             |
    +-----------+----------+-----------------------------+

    References
    ----------
    * DICOM Standard, Part 7,
      :dcm:`Annex D.3.3.7 <part07/sect_D.3.3.7.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new User Identity (AC) Item."""

    def from_primitive(self, primitive: UserIdentityNegotiation) -> None:
        """Set the item's values using an User Identity primitive.

        Parameters
        ----------
        primitive : pdu_primitives.UserIdentityNegotiation
            The primitive to use to set the Item's field values.
        """

    def to_primitive(self) -> UserIdentityNegotiation:
        """Return an  User Identity primitive from the current Item.

        Returns
        -------
        pdu_primitives.UserIdentityNegotiation
            The primitive representation of the current Item.
        """

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def response(self) -> bytes | None:
        """Return the item's *Server Response* field value."""

    @property
    def server_response_length(self) -> int:
        """Return the item's *Server Response Length* field value."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

class PresentationDataValueItem(PDUItem):
    """A Presentation Data Value Item.

    Presentation Data Value (PDV) Items are used to contain DIMSE Messages
    that have been fragmented into Command and Data fragments, with each
    fragment placed into its own PDV Item.

    Notes
    -----
    A Presentation Data Value Item requires the following parameters:

       * Item length (1)
       * Presentation context ID (1)
       * Presentation data value (1)

    **Encoding**

    When encoded, a Presentation Data Value Item has the following
    structure, taken from Tables 9.24 of the DICOM Standard (offsets shown with
    Python indexing). Items are always encoded using Big Endian.

    +---------------------------+----------+-----------------------------+
    | Offset                    | Length   | Description                 |
    +===========================+==========+=============================+
    | 0                         | 4        | Item length                 |
    +---------------------------+----------+-----------------------------+
    | 4                         | 1        | Presentation context ID     |
    +---------------------------+----------+-----------------------------+
    | 5                         | Variable | Presentation data value     |
    +---------------------------+----------+-----------------------------+

    References
    ----------
    * DICOM Standard, Part 8,
      :dcm:`Annex E <part08/chapter_E.html>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.5.1 <part08/sect_9.3.5.html#sect_9.3.5.1>`
    * DICOM Standard, Part 8,
      :dcm:`Section 9.3.1<part08/sect_9.3.html#sect_9.3.1>`
    """

    def __init__(self) -> None:
        """Initialise a new Presentation Data Value Item."""

    @property
    def context_id(self) -> int | None:
        """Return the item's *Presentation Context ID* field value."""

    @property
    def data(self) -> bytes | None:
        """Return the item's *Presentation Data Value* field value."""

    @property
    def item_length(self) -> int:
        """Return the item's *Item Length* field value as :class:`int`."""

    @property
    def item_type(self) -> int:
        """Raise NotImplementedError as Presentation Data Value Items have no *Item Type* field."""

    @property
    def message_control_header_byte(self) -> str:
        """Return the message control header byte as a formatted string."""

    def __str__(self) -> str:
        """Return a string representation of the Item."""

PDU_ITEM_TYPES = ...
_TYPE_TO_PDU_ITEM = ...
