"""This type stub file was generated by pyright."""

from types import TracebackType
from typing import TYPE_CHECKING, Any, TypeVar

from pydicom.dataset import Dataset
from pynetdicom.ae import ApplicationEntity
from pynetdicom.association import Association
from pynetdicom.dimse import DIMSEServiceProvider
from pynetdicom.dimse_primitives import C_ECHO, C_FIND, C_GET, C_MOVE, C_STORE, DIMSEPrimitive, DimseServiceType
from pynetdicom.presentation import PresentationContext
from pynetdicom.status import (
    GENERAL_STATUS,
    NON_PATIENT_SERVICE_CLASS_STATUS,
    QR_FIND_SERVICE_CLASS_STATUS,
    RELEVANT_PATIENT_SERVICE_CLASS_STATUS,
    STORAGE_SERVICE_CLASS_STATUS,
    SUBSTANCE_ADMINISTRATION_SERVICE_CLASS_STATUS,
    VERIFICATION_SERVICE_CLASS_STATUS,
    StatusDictType,
)

if TYPE_CHECKING:
    _QR = C_FIND | C_MOVE | C_GET
StatusType = int | Dataset
DatasetType = Dataset | None
UserReturnType = tuple[StatusType, DatasetType]
_T = TypeVar('_T', bound=DIMSEPrimitive)
_ExcInfoType = tuple[None, None, None] | tuple[type[BaseException], BaseException, TracebackType]
DestinationType = tuple[str, int] | tuple[str, int, dict[str, Any]]
LOGGER = ...

class attempt:
    """Context manager for sending replies when an exception is raised.

    The code within the context is executed, and if an exception is raised
    then it's logged and a DIMSE message is sent to the peer using the
    set error message and status code.
    """

    def __init__(self, rsp: DimseServiceType, dimse: DIMSEServiceProvider, cx_id: int) -> None: ...
    def __enter__(self) -> attempt: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> bool | None: ...
    @property
    def success(self) -> bool:
        """Return `True` if the code within the context executed without raising an exception, `False` otherwise."""

class ServiceClass:
    """The base class for all the service classes.

    Attributes
    ----------
    assoc : association.Association
        The association instance offering the service.
    """

    statuses = GENERAL_STATUS
    def __init__(self, assoc: Association) -> None:
        """Create a new ServiceClass."""

    @property
    def ae(self) -> ApplicationEntity:
        """Return the AE."""

    @property
    def dimse(self) -> DIMSEServiceProvider:
        """Return the DIMSE service provider."""

    def is_cancelled(self, msg_id: int) -> bool:
        """Return True if a C-CANCEL message with `msg_id` has been received.

        .. versionadded:: 1.2

        Parameters
        ----------
        msg_id : int
            The (0000,0120) *Message ID Being Responded To* value to use to
            match against.

        Returns
        -------
        bool
            ``True`` if a C-CANCEL message has been received with a *Message ID
            Being Responded To* corresponding to `msg_id`, ``False`` otherwise.
        """

    def is_valid_status(self, status: int) -> bool:
        """Return ``True`` if `status` is valid for the service class.

        Parameters
        ----------
        status : int
            The Status value to check for validity.

        Returns
        -------
        bool
            ``True`` if the status is valid, ``False`` otherwise.
        """

    def SCP(self, req: Any, context: PresentationContext) -> None:
        """Concrete subclasses override this method to implement the corresponding service class.

        Parameters
        ----------
        req : A DIMSE message primitive
            The message request primitive sent by the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

    def validate_status(self, status: int | Dataset, rsp: _T) -> _T:
        """Validate `status` and set `rsp.Status` accordingly.

        Parameters
        ----------
        status : pydicom.dataset.Dataset or int
            A Dataset containing a Status element or an int.
        rsp : dimse_primitive
            The response primitive to be sent to the peer.

        Returns
        -------
        rsp : dimse_primitive
            The response primitie to be sent to the peer (containing a valid
            Status parameter).
        """

class VerificationServiceClass(ServiceClass):
    """Implementation of the Verification Service Class."""

    statuses = VERIFICATION_SERVICE_CLASS_STATUS
    def SCP(self, req: C_ECHO, context: PresentationContext) -> None:
        """Define the SCP implementation for the Verification Service Class.

        Will always return 0x0000 (Success) unless the user returns a different
        (valid) status value from the handler bound to `evt.EVT_C_ECHO`.

        Parameters
        ----------
        req : dimse_primitives.C_ECHO
            The C-ECHO request primitive sent by the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

class StorageServiceClass(ServiceClass):
    """Implementation of the Storage Service Class."""

    uid = ...
    statuses = STORAGE_SERVICE_CLASS_STATUS
    def SCP(self, req: C_STORE, context: PresentationContext) -> None:
        """Define the SCP implementation for the Storage Service Class.

        Parameters
        ----------
        req : dimse_primitives.C_STORE
            The C-STORE request primitive sent by the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

class QueryRetrieveServiceClass(ServiceClass):
    """Implementation of the Query/Retrieve Service Class."""

    statuses: StatusDictType
    _BULK_DATA_KEYWORDS = ...
    _SUPPORTED_UIDS = ...
    def SCP(self, req: _QR, context: PresentationContext) -> None:
        """Define the SCP implementation for the Query/Retrieve Service Class.

        Parameters
        ----------
        req : dimse_primitives.C_FIND or C_GET or C_MOVE
            The request primitive received from the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

class BasicWorklistManagementServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Basic Worklist Management Service Class."""

    statuses = QR_FIND_SERVICE_CLASS_STATUS
    _SUPPORTED_UIDS = ...
    def SCP(self, req: _QR, context: PresentationContext) -> None:
        """Define the SCP implementation for Basic Worklist Management.

        Parameters
        ----------
        req : dimse_primitives.C_FIND
            The C-FIND request primitive received from the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

class ColorPaletteQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Color Palette QR Service."""

class DefinedProcedureProtocolQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Defined Procedure Protocol QR Service."""

class HangingProtocolQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Hanging Protocol QR Service."""

class ImplantTemplateQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Implant Template QR Service."""

class InventoryQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Inventory QR Service.

    .. versionadded:: 2.1
    """

class NonPatientObjectStorageServiceClass(StorageServiceClass):
    """Implementation of the Non-Patient Object Storage Service."""

    statuses = NON_PATIENT_SERVICE_CLASS_STATUS

class ProtocolApprovalQueryRetrieveServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Protocol Approval QR Service."""

class RelevantPatientInformationQueryServiceClass(ServiceClass):
    """Implementation of the Relevant Patient Information Query."""

    statuses = RELEVANT_PATIENT_SERVICE_CLASS_STATUS
    def SCP(self, req: C_FIND, context: PresentationContext) -> None:
        """Define the SCP implementation for the Relevant Patient Information Query Service Class.

        Parameters
        ----------
        req : dimse_primitives.C_FIND
            The C-FIND request primitive sent by the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """

class SubstanceAdministrationQueryServiceClass(QueryRetrieveServiceClass):
    """Implementation of the Substance Administration Query Service."""

    statuses = SUBSTANCE_ADMINISTRATION_SERVICE_CLASS_STATUS
    _SUPPORTED_UIDS = ...
    def SCP(self, req: _QR, context: PresentationContext) -> None:
        """Define the SCP implementation for the Substance Administration Query Service Class.

        Parameters
        ----------
        req : dimse_primitives.C_FIND
            The C-FIND request primitive sent by the peer.
        context : presentation.PresentationContext
            The presentation context that the SCP is operating under.
        """
