"""This type stub file was generated by pyright."""

from enum import IntEnum

from pydicom.dataset import Dataset

StatusDictType = dict[int, tuple[str, str]]
GENERAL_STATUS: StatusDictType = ...
VERIFICATION_SERVICE_CLASS_STATUS = GENERAL_STATUS
STORAGE_SERVICE_CLASS_STATUS: StatusDictType = ...
QR_FIND_SERVICE_CLASS_STATUS: StatusDictType = ...
QR_MOVE_SERVICE_CLASS_STATUS: StatusDictType = ...
QR_GET_SERVICE_CLASS_STATUS: StatusDictType = ...
MODALITY_WORKLIST_SERVICE_CLASS_STATUS: StatusDictType = ...
RELEVANT_PATIENT_SERVICE_CLASS_STATUS: StatusDictType = ...
SUBSTANCE_ADMINISTRATION_SERVICE_CLASS_STATUS: StatusDictType = ...
NON_PATIENT_SERVICE_CLASS_STATUS: StatusDictType = ...
PROCEDURE_STEP_STATUS: StatusDictType = ...
PRINT_JOB_MANAGEMENT_SERVICE_CLASS_STATUS: StatusDictType = ...
STORAGE_COMMITMENT_SERVICE_CLASS_STATUS = GENERAL_STATUS
STORAGE_MANAGEMENT_SERVICE_CLASS_STATUS: StatusDictType = ...
APPLICATION_EVENT_LOGGING_SERVICE_CLASS_STATUS: StatusDictType = ...
MEDIA_CREATION_MANAGEMENT_SERVICE_CLASS_STATUS: StatusDictType = ...
UNIFIED_PROCEDURE_STEP_SERVICE_CLASS_STATUS: StatusDictType = ...
RT_MACHINE_VERIFICATION_SERVICE_CLASS_STATUS: StatusDictType = ...

def code_to_status(code: int) -> Dataset:
    """Return a :class:`~pydicom.dataset.Dataset` with a *Status* element value of `code`."""
    ...

def code_to_category(code: int) -> str:
    """Return a *Status* category as :class:`str` or ``'Unknown'`` if not recognized."""
    ...

class Status(IntEnum):
    """Constants for common status codes.

    .. versionadded:: 1.5

    New constants can be added with the ``Status.add(name, code)`` method but
    the documentation for it is missing due to a bug in Sphinx. `name` is
    the variable name of the constant to add as a :class:`str` and `code` is
    the corresponding status code as an :class:`int`.

    Examples
    --------
    ::

        from pynetdicom.status import Status

        # Customize the class
        Status.add('UNABLE_TO_PROCESS', 0xC000)

        def handle_store(event):
            try:
                event.dataset.save_as('temp.dcm')
            except:
                return Status.UNABLE_TO_PROCESS

            return Status.SUCCESS

    """

    SUCCESS = ...
    CANCEL = ...
    PENDING = ...
    MOVE_DESTINATION_UNKNOWN = ...
    @classmethod
    def add(cls, name: str, code: int) -> None:
        """Add a new constant to `Status`.

        Parameters
        ----------
        name : str
            The name of the constant to add.
        code : int
            The status code corresponding to the name.
        """
        ...
