"""This type stub file was generated by pyright."""

import queue
import socket
import ssl
from collections.abc import Callable
from socketserver import BaseRequestHandler, TCPServer, ThreadingMixIn
from typing import TYPE_CHECKING, Any

from pynetdicom import evt
from pynetdicom.ae import ApplicationEntity
from pynetdicom.association import Association
from pynetdicom.dul import _QueueType  # pyright: ignore[reportPrivateUsage]
from pynetdicom.events import Handler
from pynetdicom.pdu_primitives import A_ASSOCIATE
from pynetdicom.presentation import PresentationContext

"""
This type stub file was generated by pyright.
"""
_HAS_SSL = ...
if TYPE_CHECKING: ...
LOGGER = ...

class T_CONNECT:
    """A TRANSPORT CONNECTION primitive.

    .. versionadded:: 2.0

    Attributes
    ----------
    request : pynetdicom.pdu_primitives.A_ASSOCIATE
        The A-ASSOCIATE (request) primitive that generated the TRANSPORT CONNECTION
        primitive.
    """

    def __init__(self, request: A_ASSOCIATE) -> None:
        """Create a new TRANSPORT CONNECTION primitive.

        Parameters
        ----------
        request : pynetdicom.pdu_primitives.A_ASSOCIATE
            The A-ASSOCIATE (request) primitive to use when making a connection with
            a peer.
        """
        ...

    @property
    def address(self) -> tuple[str, int]:
        """Return the peer's ``(str: IP address, int: port)``."""
        ...

    @property
    def result(self) -> str:
        """Return the result of the connection attempt as :class:`str`.

        Parameters
        ----------
        str
            The result of the connection attempt, ``"Evt2"`` if the connection
            succeeded, ``"Evt17"`` if it failed.

        Returns
        -------
        str
            The result of the connection attempt, ``"Evt2"`` if the connection
            succeeded, ``"Evt17"`` if it failed.
        """
        ...

    @result.setter
    def result(self, value: str) -> None: ...

class AssociationSocket:
    """A wrapper for a `socket.socket` object.

    .. versionadded:: 1.2

    Provides an interface for ``socket`` that is integrated
    nicely with an :class:`~pynetdicom.association.Association` instance
    and the state machine.

    Attributes
    ----------
    select_timeout : float or None
        The timeout (in seconds) that :func:`select.select` calls in
        :meth:`ready` will block for (default ``0.5``). A value of ``0``
        specifies a poll and never blocks. A value of ``None`` blocks until a
        connection is ready.
    socket : socket.socket or None
        The wrapped socket, will be ``None`` if :meth:`close` is called.
    """

    def __init__(
        self, assoc: Association, client_socket: socket.socket | None = ..., address: tuple[str, int] = ...
    ) -> None:
        """Create a new :class:`AssociationSocket`.

        Parameters
        ----------
        assoc : association.Association
            The :class:`~pynetdicom.association.Association` instance that will
            be using the socket to communicate.
        client_socket : socket.socket, optional
            The ``socket.socket`` to wrap,
            if not supplied then a new socket will be created instead.
        address : 2-tuple, optional
            If *client_socket* is ``None`` then this is the ``(host, port)`` to
            bind the newly created socket to, which by default will be
            ``("", 0)``.
        """
        ...

    @property
    def assoc(self) -> Association:
        """Return the parent :class:`~pynetdicom.association.Association` instance."""
        ...

    def close(self) -> None:
        """Close the connection to the peer and shutdown the socket.

        Sets :attr:`AssociationSocket.socket` to ``None`` once complete.

        **Events Emitted**

        - Evt17: Transport connection closed
        """
        ...

    def connect(self, primitive: T_CONNECT) -> None:
        """Try and connect to a remote using connection details from  `primitive`.

        .. versionchanged:: 2.0

            Changed to take a :class:`~pynetdicom.transport.T_CONNECT` primitive rather
            than an address tuple.

        Parameters
        ----------
        primitive : pynetdicom.transport.T_CONNECT
            The TRANSPORT CONNECT primitive to use when connecting to a peer.
        """
        ...

    @property
    def event_queue(self) -> queue.Queue[str]:
        """Return the :class:`~pynetdicom.association.Association`'s service event queue."""
        ...

    def get_local_addr(self, host: tuple[str, int] = ...) -> str:
        """Return an address for the local computer as :class:`str`.

        Parameters
        ----------
        host : tuple[str, int]
            The host's ``(addr: str, port: int)`` when trying to determine the local
            address.
        """
        ...

    @property
    def provider_queue(self) -> _QueueType:
        """Return the :class:`~pynetdicom.association.Association`'s service provider queue."""
        ...

    @property
    def ready(self) -> bool:
        """Return ``True`` if there is data available to be read.

        *Events Emitted*

        - None
        - Evt17: Transport connection closed

        Returns
        -------
        bool
            ``True`` if the socket has data ready to be read, ``False``
            otherwise.
        """
        ...

    def recv(self, nr_bytes: int) -> bytearray:
        """Read `nr_bytes` from the socket.

        *Events Emitted*

        - None

        Parameters
        ----------
        nr_bytes : int
            The number of bytes to attempt to read from the socket.

        Returns
        -------
        bytearray
            The data read from the socket.
        """
        ...

    def send(self, bytestream: bytes) -> None:
        """Try and send the data in `bytestream` to the remote.

        *Events Emitted*

        - None
        - Evt17: Transport connected closed.

        Parameters
        ----------
        bytestream : bytes
            The data to send to the remote.
        """
        ...

    def __str__(self) -> str:
        """Return the string output for ``socket``."""
        ...

    @property
    def tls_args(self) -> tuple[ssl.SSLContext, str] | None:
        """Get or set the TLS context and hostname.

        Parameters
        ----------
        tls_args : tuple[ssl.SSLContext, str] or None
            If the socket should be wrapped by TLS then this is
            ``(context, hostname)``, where *context* is a
            :class:`ssl.SSLContext` that will be used to wrap the socket and
            *hostname* is the value to use for the *server_hostname* keyword
            argument for :meth:`SSLContext.wrap_socket()
            <ssl.SSLContext.wrap_socket>`.

        Returns
        -------
        tuple[ssl.SSLContext, str] | None
        """
        ...

    @tls_args.setter
    def tls_args(self, tls_args: tuple[ssl.SSLContext, str] | None) -> None:
        """Set the TLS arguments for the socket."""
        ...

class RequestHandler(BaseRequestHandler):
    """Connection request handler for the ``AssociationServer``.

    .. versionadded:: 1.2

    Attributes
    ----------
    client_address : 2-tuple
        The ``(host, port)`` of the remote.
    request : socket.socket
        The (unaccepted) client socket.
    server : transport.AssociationServer or transport.ThreadedAssociationServer
        The server that received the connection request.
    """

    server: AssociationServer  # pyright: ignore[reportIncompatibleVariableOverride]

    @property
    def ae(self) -> ApplicationEntity:
        """Return the server's parent AE."""
        ...

    def handle(self) -> None:
        """Handle an association request.

        * Creates a new Association acceptor instance and configures it.
        * Sets the Association's socket to the request's socket.
        * Starts the Association reactor.
        """
        ...

    @property
    def local(self) -> tuple[str, int]:
        """Return a 2-tuple of the local server's ``(host, port)`` address."""
        ...

    @property
    def remote(self) -> tuple[str, int]:
        """Return a 2-tuple of the remote client's ``(host, port)`` address."""
        ...

class AssociationServer(TCPServer):
    """An Association server implementation.

    .. versionadded:: 1.2

    .. versionchanged:: 1.5

        Added `request_handler` keyword parameter.

    Any attempts to connect will be assumed to be from association requestors.

    The server should be started with
    :meth:`serve_forever(poll_interval)<AssociationServer.serve_forever>`,
    where *poll_interval* is the timeout (in seconds) that the
    :func:`select.select` call will block for (default ``0.5``). A value of
    ``0`` specifies a poll and never blocks. A value of ``None`` blocks until
    a connection is ready.

    Attributes
    ----------
    ae : ae.ApplicationEntity
        The parent AE that is running the server.
    request_queue_size : int
        Default ``5``.
    server_address : tuple[str, int]
        The ``(host: str, port: int)`` that the server is running on.
    """

    def __init__(
        self,
        ae: ApplicationEntity,
        address: tuple[str, int],
        ae_title: str,
        contexts: list[PresentationContext],
        ssl_context: ssl.SSLContext | None = ...,
        evt_handlers: list[evt.EventHandlerType[evt.P]] | None = ...,
        request_handler: Callable[..., BaseRequestHandler] | None = ...,
    ) -> None:
        """Create a new :class:`AssociationServer`, bind a socket and start listening.

        Parameters
        ----------
        ae : ae.ApplicationEntity
            The parent AE that's running the server.
        address : tuple[str, int]
            The ``(host: str, port: int)`` that the server should run on.
        ae_title : str
            The AE title of the SCP.
        contexts : list of presentation.PresentationContext
            The SCPs supported presentation contexts.
        ssl_context : ssl.SSLContext, optional
            If TLS is to be used then this should be the
            :class:`ssl.SSLContext` used to wrap the client sockets, otherwise
            if ``None`` then no TLS will be used (default).
        evt_handlers : list of 2- or 3-tuple, optional
            A list of ``(event, callable)`` or ``(event, callable, args)``,
            the *callable* function to run when *event* occurs and the
            optional extra *args* to pass to the callable.
        request_handler : type
            The request handler class; an instance of this class
            is created for each request. Should be a subclass of
            :class:`~socketserver.BaseRequestHandler`.
        """
        ...

    def bind(self, event: evt.EventType, handler: Handler[evt.P], args: list[Any] | None = ...) -> None:
        """Bind a callable `handler` to an `event`.

        .. versionadded:: 1.3

        .. versionchanged:: 1.5

            Added `args` keyword parameter.

        Parameters
        ----------
        event : namedtuple
            The event to bind the function to.
        handler : callable
            The function that will be called if the event occurs.
        args : list, optional
            Optional extra arguments to be passed to the handler (default:
            no extra arguments passed to the handler).
        """
        ...

    @property
    def active_associations(self) -> list[Association]:
        """Return the server's running :class:`~pynetdicom.association.Association` acceptor instances."""
        ...

    def get_events(self) -> list[evt.EventType]:
        """Return a list of currently bound events.

        .. versionadded:: 1.3
        """
        ...

    def get_handlers(self, event: evt.EventType) -> evt.HandlerArgType[evt.P]:
        """Return handlers bound to a specific `event`.

        .. versionadded:: 1.3

        .. versionchanged:: 1.5

            Returns a 2-tuple of (callable, args) or list of 2-tuple.

        Parameters
        ----------
        event : namedtuple
            The event bound to the handlers.

        Returns
        -------
        2-tuple of (callable, args), list of 2-tuple
            If the event is a notification event then returns a list of
            2-tuples containing the callable functions bound to `event` and
            the arguments passed to the callable as ``(callable, args)``. If
            the event is an intervention event then returns either a 2-tuple of
            (callable, args) if a handler is bound to the event or
            ``(None, None)`` if no handler has been bound.
        """
        ...

    def get_request(self) -> tuple[socket.socket, tuple[str, int]]:
        """Handle a connection request.

        If :attr:`~AssociationServer.ssl_context` is set then the client socket
        will be wrapped using
        :meth:`SSLContext.wrap_socket()<ssl.SSLContext.wrap_socket>`.

        Returns
        -------
        client_socket : socket.socket
            The connection request.
        address : 2-tuple
            The client's address as ``(host, port)``.
        """
        ...

    def process_request(
        self, request: socket.socket | tuple[bytes, socket.socket], client_address: tuple[str, int] | str
    ) -> None:
        """Process a connection request."""
        ...

    def server_bind(self) -> None:
        """Bind the socket and set the socket options.

        - ``socket.SO_REUSEADDR`` is set to ``1``
        - socket.settimeout is used to set to
          :attr:`AE.network_timeout
          <pynetdicom.ae.ApplicationEntity.network_timeout>` unless the
          value is ``None`` in which case it will be left unset.
        """
        ...

    def server_close(self) -> None:
        """Close the server."""
        ...

    def service_actions(self) -> None:
        """Execute actions as called by the `serve_forever()` loop."""
        ...

    def shutdown(self) -> None:
        """Completely shutdown the server and close its socket."""
        ...

    @property
    def ssl_context(self) -> ssl.SSLContext | None:
        """Return the :class:`ssl.SSLContext` (if available).

        Parameters
        ----------
        context : ssl.SSLContext or None
            If TLS is to be used then this should be the
            :class:`ssl.SSLContext` used to wrap the client sockets, otherwise
            if ``None`` then no TLS will be used (default).
        """
        ...

    @ssl_context.setter
    def ssl_context(self, context: ssl.SSLContext | None) -> None:
        """Set the SSL context for the socket."""
        ...

    def unbind(self, event: evt.EventType, handler: evt.Handler[evt.P]) -> None:
        """Unbind a callable `handler` from an `event`.

        .. versionadded:: 1.3

        Parameters
        ----------
        event :
            The event to unbind the function from.
        handler :
            The function that will no longer be called if the event occurs.
        """
        ...

class ThreadedAssociationServer(ThreadingMixIn, AssociationServer):
    """An :class:`AssociationServer` suitable for threading.

    .. versionadded:: 1.2
    """

    def process_request_thread(
        self, request: socket.socket | tuple[bytes, socket.socket], client_address: tuple[str, int] | str
    ) -> None:
        """Process a connection request."""
        ...
