"""This type stub file was generated by pyright."""

from collections.abc import Callable, Iterator
from contextlib import contextmanager
from io import BytesIO
from typing import Any, ParamSpec

from pydicom.uid import UID

"""Various utility functions."""
HAVE_CTYPES = ...
LOGGER = ...

P = ParamSpec('P')

def decode_bytes(encoded_value: bytes) -> str:
    """Return the decoded string from `encoded_value`.

    .. versionadded:: 2.0

    Parameters
    ----------
    encoded_value : bytes
        The encoded value to be decoded.

    Returns
    -------
    str
        The decoded ISO 646 (ASCII) string.
    """

def make_target(target_fn: Callable[P, Any]) -> Callable[P, Any]:
    """Wrap `target_fn` in a thunk that passes all contextvars from the current context.

    It is assumed that `target_fn` is the target of a new ``threading.Thread``.

    Requires:

    * :attr:`~pynetdicom._config.PASS_CONTEXTVARS` set ``True``

    If the requirements are not met, the original `target_fn` is returned.

    Parameters
    ----------
    target_fn : Callable
        The function to wrap

    Returns
    -------
    Callable
        The wrapped `target_fn` if requirements are met, else the original
        `target_fn`.
    """

def pretty_bytes(
    bytestream: bytes | BytesIO,
    prefix: str = ...,
    delimiter: str = ...,
    items_per_line: int = ...,
    max_size: int | None = ...,
    suffix: str = ...,
) -> list[str]:
    """Turn the bytestring `bytestream` into a `list` of nicely formatted `str`.

    Parameters
    ----------
    bytestream : bytes or io.BytesIO
        The bytes to convert to a nicely formatted string list
    prefix : str
        Insert `prefix` at the start of every item in the output string list
    delimiter : str
        Delimit each of the bytes in `bytestream` using `delimiter`
    items_per_line : int
        The number of bytes in each item of the output string list.
    max_size : int or None
        The maximum number of bytes to add to the output string list. A value
        of ``None`` indicates that all of `bytestream` should be output.
    suffix : str
        Append `suffix` to the end of every item in the output string list

    Returns
    -------
    list of str
        The output string list
    """

def set_ae(value: str | None, name: str, allow_empty: bool = ..., allow_none: bool = ...) -> str | None:
    """Convert `value` to an **AE** like parameter and apply validation.

    Parameters
    ----------
    value : str or None
        The value to be converted.
    name : str
        The name of the parameter being converted.
    allow_empty : bool, optional
        If ``True`` (default) skip validation when an empty string or ``None``
        is used.

    Returns
    -------
    str or None
        If ``allow_empty`` is ``True`` then may return ``None``, otherwise
        the string will be returned.
    """

def set_uid(
    value: None | str | bytes | UID, name: str, allow_empty: bool = ..., allow_none: bool = ..., validate: bool = ...
) -> UID | None:
    """Convert `value` to a :class:`UID` and apply validation.

    Parameters
    ----------
    value : str, bytes, UID (and optionally None)
        The value to be converted.
    name : str
        The name of the parameter being converted.
    allow_empty : bool, optional
        If ``True`` then allow an empty UID (default).
    allow_none : bool, optional
        Allow the returned value to be ``None`` if `value` is ``None``
        (default ``True``).
    validate : bool, optional
        If ``True`` (default) perform validation of the UID using
        :func:`~pynetdicom.utils.validate_uid` and raise a
        :class:`ValueError` exception if the validation fails. If ``False``
        return the UID without performing and validation.

    Returns
    -------
    pydicom.uid.UID or None
        If ``allow_none`` is ``True`` then may return ``None``, otherwise
        only a UID will be returned.
    """

@contextmanager
def set_timer_resolution(resolution: float | None) -> Iterator[None]:
    """Set the Windows timer resolution.

    Parameters
    ----------
    resolution: float or None
        The desired timer resolution in milliseconds. If `resolution` is not in
        the allowed range then the timer resolution will be set to the minimum
        or maximum allowed instead. If ``None`` then the timer resolution will
        not be changed.

    Yields
    ------
    None
    """

def validate_uid(uid: UID) -> bool:
    """Return True if `uid` is considered valid.

    If :attr:`~pynetdicom._config.ENFORCE_UID_CONFORMANCE` is ``True`` then the
    following rules apply:

    * 1-64 characters, inclusive
    * Each component may not start with 0 unless the component itself is 0
    * Components are separated by ``.``
    * Valid component characters are 0-9 of the Basic G0 Set of the
      International Reference Version of ISO 646:1990 (ASCII)

    If :attr:`~pynetdicom._config.ENFORCE_UID_CONFORMANCE` is ``False`` then
    the following rules apply:

    * 1-64 characters, inclusive

    Parameters
    ----------
    uid : pydicom.uid.UID
        The UID to check for validity.

    Returns
    -------
    bool
        ``True`` if the value is considered valid, ``False`` otherwise.
    """
