"""This type stub file was generated by pyright."""

from __future__ import annotations

import argparse
import functools
from collections import OrderedDict
from typing import IO, Any

# for Python 3.10
from typing_extensions import LiteralString, Self

"""
A drop-in replacement for `argparse` that allows options to also be set via config files and/or environment variables.

:see: `configargparse.ArgumentParser`, `configargparse.add_argument`
"""
ACTION_TYPES_THAT_DONT_NEED_A_VALUE = ...
is_boolean_optional_action = ...
_parsers = ...

ConfigItem = OrderedDict[str, list[Any] | str]

def init_argument_parser(name: str = ..., **kwargs: Any) -> None:
    """Creates a global ArgumentParser instance with the given name,
    passing any args other than "name" to the ArgumentParser constructor.
    This instance can then be retrieved using get_argument_parser(..).
    """
    ...

def get_argument_parser(name: str = ..., **kwargs: Any) -> ArgumentParser:
    """Returns the global ArgumentParser instance with the given name. The 1st
    time this function is called, a new ArgumentParser instance will be created
    for the given name, and any args other than "name" will be passed on to the
    ArgumentParser constructor.
    """
    ...

class ArgumentDefaultsRawHelpFormatter(
    argparse.ArgumentDefaultsHelpFormatter, argparse.RawTextHelpFormatter, argparse.RawDescriptionHelpFormatter
):
    """HelpFormatter that adds default values AND doesn't do line-wrapping."""

    ...

class ConfigFileParser:
    """This abstract class can be extended to add support for new config file
    formats.
    """

    def get_syntax_description(self) -> Any:
        """Returns a string describing the config file syntax."""
        ...

    def parse(self, stream: IO[str]) -> ConfigItem:
        """Parses the keys and values from a config file.

        NOTE: For keys that were specified to configargparse as
        action="store_true" or "store_false", the config file value must be
        one of: "yes", "no", "on", "off", "true", "false". Otherwise an error will be raised.

        Args:
            stream (IO): A config file input stream (such as an open file object).

        Returns
        -------
            OrderedDict: Items where the keys are strings and the
            values are either strings or lists (eg. to support config file
            formats like YAML which allow lists).
        """
        ...

    def serialize(self, items: list[ConfigItem]) -> str:
        """Does the inverse of config parsing by taking parsed values and
        converting them back to a string representing config file contents.

        Args:
            items: an OrderedDict of items to be converted to the config file
                format. Keys should be strings, and values should be either strings
                or lists.

        Returns
        -------
            Contents of config file as a string
        """
        ...

class ConfigFileParserException(Exception):
    """Raised when config file parsing failed."""

    ...

class DefaultConfigFileParser(ConfigFileParser):
    """
    Based on a simplified subset of INI and YAML formats. Here is the
    supported syntax.

    .. code::

        # this is a comment
        ; this is also a comment (.ini style)
        ---            # lines that start with --- are ignored (yaml style)
        -------------------
        [section]      # .ini-style section names are treated as comments

        # how to specify a key-value pair (all of these are equivalent):
        name value     # key is case sensitive: "Name" isn't "name"
        name = value   # (.ini style)  (white space is ignored, so name = value same as name=value)
        name: value    # (yaml style)
        --name value   # (argparse style)

        # how to set a flag arg (eg. arg which has action="store_true")
        --name
        name
        name = True    # "True" and "true" are the same

        # how to specify a list arg (eg. arg which has action="append")
        fruit = [apple, orange, lemon]
        indexes = [1, 12, 35 , 40]

    """

    def get_syntax_description(self) -> LiteralString: ...
    def parse(self, stream: IO[str]) -> ConfigItem: ...
    def serialize(self, items: list[ConfigItem]) -> str: ...

class ConfigparserConfigFileParser(ConfigFileParser):
    """parses INI files using pythons configparser."""

    def get_syntax_description(self) -> LiteralString: ...
    def parse(self, stream: IO[str]) -> OrderedDict[Any, Any]: ...
    def serialize(self, items: list[ConfigItem]) -> str: ...

class YAMLConfigFileParser(ConfigFileParser):
    """Parses YAML config files. Depends on the PyYAML module.
    https://pypi.python.org/pypi/PyYAML.
    """

    def get_syntax_description(self) -> LiteralString: ...
    def parse(self, stream: IO[str]) -> OrderedDict[Any, Any]: ...
    def serialize(self, items: list[ConfigItem], default_flow_style: bool = False) -> str: ...

_QUOTED_STR_REGEX = ...
_TRIPLE_QUOTED_STR_REGEX = ...

@functools.lru_cache(maxsize=256, typed=True)
def is_quoted(text: str, triple: bool = ...) -> bool:
    """
    Detect whether a string is a quoted representation.

    :param triple: Also match tripple quoted strings.
    """
    ...

def unquote_str(text: str, triple: bool = ...) -> str:
    """
    Unquote a maybe quoted string representation.
    If the string is not detected as being a quoted representation, it returns the same string as passed.
    It supports all kinds of python quotes: ``\"\"\"``, ``'''``, ``"`` and ``'``.

    :param triple: Also unquote tripple quoted strings.
    @raises ValueError: If the string is detected as beeing quoted but literal_eval() fails to evaluate it as string.
        This would be a bug in the regex.
    """
    ...

def parse_toml_section_name(section_name: str) -> tuple[Any, ...]:
    """
    Parse a TOML section name to a sequence of strings.

    The following names are all valid:

    .. python::

        "a.b.c"            # this is best practice -> returns ("a", "b", "c")
        " d.e.f "          # same as [d.e.f] -> returns ("d", "e", "f")
        " g .  h  . i "    # same as [g.h.i] -> returns ("g", "h", "i")
        ' j . "ʞ" . "l" '  # same as [j."ʞ"."l"], double or simple quotes here are supported. -> returns ("j", "ʞ", "l")
    """
    ...

def get_toml_section(data: dict[str, Any], section: str) -> dict[str, Any] | None:
    """
    Given some TOML data (as loaded with `toml.load()`), returns the requested section of the data.
    Returns ``None`` if the section is not found.
    """
    ...

class TomlConfigParser(ConfigFileParser):
    """
    Create a TOML parser bounded to the list of provided sections.

    Example::
        # this is a comment
        [tool.my-software] # TOML section table.
        # how to specify a key-value pair
        format-string = "restructuredtext" # strings must be quoted
        # how to set an arg which has action="store_true"
        warnings-as-errors = true
        # how to set an arg which has action="count" or type=int
        verbosity = 1
        # how to specify a list arg (eg. arg which has action="append")
        repeatable-option = ["https://docs.python.org/3/objects.inv",
                       "https://twistedmatrix.com/documents/current/api/objects.inv"]
        # how to specify a multiline text:
        multi-line-text = '''
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Vivamus tortor odio, dignissim non ornare non, laoreet quis nunc.
            Maecenas quis dapibus leo, a pellentesque leo.
            '''

    Note that the config file fragment above is also valid for the `IniConfigParser` class and would be parsed the same manner.
    Thought, any valid TOML config file will not be necessarly parsable with `IniConfigParser` (INI files must be rigorously indented whereas TOML files).

    See the `TOML specification <>`_ for details.
    """

    def __init__(self, sections: list[str]) -> None:
        """:param sections: The section names bounded to the new parser."""
        ...

    def __call__(self) -> Self: ...
    def parse(self, stream: IO[str]) -> OrderedDict[Any, Any]:
        """Parses the keys and values from a TOML config file."""
        ...

    def get_syntax_description(self) -> LiteralString: ...

class IniConfigParser(ConfigFileParser):
    r"""
    Create a INI parser bounded to the list of provided sections.
    Optionaly convert multiline strings to list.

    Example (if split_ml_text_to_list=False)::

        # this is a comment
        ; also a comment
        [my-software]
        # how to specify a key-value pair
        format-string: restructuredtext
        # white space are ignored, so name = value same as name=value
        # this is why you can quote strings
        quoted-string = '\thello\tmom...  '
        # how to set an arg which has action="store_true"
        warnings-as-errors = true
        # how to set an arg which has action="count" or type=int
        verbosity = 1
        # how to specify a list arg (eg. arg which has action="append")
        repeatable-option = ["https://docs.python.org/3/objects.inv",
                       "https://twistedmatrix.com/documents/current/api/objects.inv"]
        # how to specify a multiline text:
        multi-line-text =
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Vivamus tortor odio, dignissim non ornare non, laoreet quis nunc.
            Maecenas quis dapibus leo, a pellentesque leo.

    Example (if split_ml_text_to_list=True)::

        # the same rules are applicable with the following changes:
        [my-software]
        # how to specify a list arg (eg. arg which has action="append")
        repeatable-option = # Just enter one value per line (the list literal format can also be used)
            https://docs.python.org/3/objects.inv
            https://twistedmatrix.com/documents/current/api/objects.inv
        # how to specify a multiline text (you have to quote it):
        multi-line-text = '''
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Vivamus tortor odio, dignissim non ornare non, laoreet quis nunc.
            Maecenas quis dapibus leo, a pellentesque leo.
            '''
    """

    def __init__(self, sections: list[str], split_ml_text_to_list: bool) -> None:
        """
        :param sections: The section names bounded to the new parser.
        :split_ml_text_to_list: Wether to convert multiline strings to list
        """
        ...

    def __call__(self) -> Self: ...
    def parse(self, stream: IO[str]) -> OrderedDict[Any, Any]:
        """Parses the keys and values from an INI config file."""
        ...

    def get_syntax_description(self) -> LiteralString: ...

class CompositeConfigParser(ConfigFileParser):
    """
    Createa a config parser composed by others `ConfigFileParser`s.

    The composite parser will successively try to parse the file with each parser,
    until it succeeds, else raise execption with all encountered errors.
    """

    def __init__(self, config_parser_types: list[type[ConfigFileParser]]) -> None: ...
    def __call__(self) -> Self: ...
    def parse(self, stream: IO[str]) -> OrderedDict[Any, Any]: ...
    def get_syntax_description(self) -> LiteralString: ...

_COMMAND_LINE_SOURCE_KEY = ...
_ENV_VAR_SOURCE_KEY = ...
_CONFIG_FILE_SOURCE_KEY = ...
_DEFAULTS_SOURCE_KEY = ...

class ArgumentParser(argparse.ArgumentParser):
    """Drop-in replacement for `argparse.ArgumentParser` that adds support for
    environment variables and ``.ini`` or ``.yaml-style`` config files.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        r"""Supports args of the `argparse.ArgumentParser` constructor
        as \*\*kwargs, as well as the following additional args.

        Arguments:
            add_config_file_help: Whether to add a description of config file
                syntax to the help message.
            add_env_var_help: Whether to add something to the help message for
                args that can be set through environment variables.
            auto_env_var_prefix: If set to a string instead of None, all config-
                file-settable options will become also settable via environment
                variables whose names are this prefix followed by the config
                file key, all in upper case. (eg. setting this to ``foo_`` will
                allow an arg like ``--my-arg`` to also be set via the FOO_MY_ARG
                environment variable)
            default_config_files: When specified, this list of config files will
                be parsed in order, with the values from each config file
                taking precedence over previous ones. This allows an application
                to look for config files in multiple standard locations such as
                the install directory, home directory, and current directory.
                Also, shell \* syntax can be used to specify all conf files in a
                directory. For example::

                    ["/etc/conf/app_config.ini",
                    "/etc/conf/conf-enabled/*.ini",
                    "~/.my_app_config.ini",
                    "./app_config.txt"]

            ignore_unknown_config_file_keys: If true, settings that are found
                in a config file but don't correspond to any defined
                configargparse args will be ignored. If false, they will be
                processed and appended to the commandline like other args, and
                can be retrieved using parse_known_args() instead of parse_args()
            config_file_open_func: function used to open a config file for reading
                or writing. Needs to return a file-like object.
            config_file_parser_class: configargparse.ConfigFileParser subclass
                which determines the config file format. configargparse comes
                with DefaultConfigFileParser and YAMLConfigFileParser.
            args_for_setting_config_path: A list of one or more command line
                args to be used for specifying the config file path
                (eg. ["-c", "--config-file"]). Default: []
            config_arg_is_required: When args_for_setting_config_path is set,
                set this to True to always require users to provide a config path.
            config_arg_help_message: the help message to use for the
                args listed in args_for_setting_config_path.
            args_for_writing_out_config_file: A list of one or more command line
                args to use for specifying a config file output path. If
                provided, these args cause configargparse to write out a config
                file with settings based on the other provided commandline args,
                environment variants and defaults, and then to exit.
                (eg. ["-w", "--write-out-config-file"]). Default: []
            write_out_config_file_arg_help_message: The help message to use for
                the args in args_for_writing_out_config_file.
        """
        ...

    def parse_args(  # type: ignore[override]
        self,
        args: list[str] | str | None = ...,
        namespace: Namespace | None = ...,
        config_file_contents: str | None = ...,
        env_vars: dict[str, str] = ...,
    ) -> Namespace:
        """Supports all the same args as the `argparse.ArgumentParser.parse_args()`,
        as well as the following additional args.

        Arguments:
            args: a list of args as in argparse, or a string (eg. "-x -y bla")
            config_file_contents: String. Used for testing.
            env_vars: Dictionary. Used for testing.

        Returns
        -------
            argparse.Namespace: namespace
        """
        ...

    def parse_known_args(self, args=..., namespace=..., config_file_contents=..., env_vars=..., ignore_help_args=...):
        """Supports all the same args as the `argparse.ArgumentParser.parse_args()`,
        as well as the following additional args.

        Arguments:
            args: a list of args as in argparse, or a string (eg. "-x -y bla")
            config_file_contents (str). Used for testing.
            env_vars (dict). Used for testing.
            ignore_help_args (bool): This flag determines behavior when user specifies ``--help`` or ``-h``. If False,
                it will have the default behavior - printing help and exiting. If True, it won't do either.

        Returns
        -------
            tuple[argparse.Namespace, list[str]]: tuple namescpace, unknown_args
        """
        ...

    def get_source_to_settings_dict(self):  # -> OrderedDict[Any, Any]:
        """
        If called after `parse_args()` or `parse_known_args()`, returns a dict that contains up to 4 keys corresponding
        to where a given option's value is coming from:
        - "command_line"
        - "environment_variables"
        - "config_file"
        - "defaults"
        Each such key, will be mapped to another dictionary containing the options set via that method. Here the key
        will be the option name, and the value will be a 2-tuple of the form (`argparse.Action` obj, `str` value).

        Returns
        -------
            dict[str, dict[str, tuple[argparse.Action, str]]]: source to settings dict
        """
        ...

    def write_config_file(self, parsed_namespace, output_file_paths, exit_after=...):  # -> None:
        """Write the given settings to output files.

        Args:
            parsed_namespace: namespace object created within parse_known_args()
            output_file_paths: any number of file paths to write the config to
            exit_after: whether to exit the program after writing the config files
        """
        ...

    def get_command_line_key_for_unknown_config_file_setting(self, key):
        """Compute a commandline arg key to be used for a config file setting
        that doesn't correspond to any defined configargparse arg (and so
        doesn't have a user-specified commandline arg key).

        Args:
            key: The config file key that was being set.

        Returns
        -------
            str: command line key
        """
        ...

    def get_items_for_config_file_output(self, source_to_settings, parsed_namespace):  # -> OrderedDict[Any, Any]:
        """Converts the given settings back to a dictionary that can be passed
        to ConfigFormatParser.serialize(..).

        Args:
            source_to_settings: the dictionary described in parse_known_args()
            parsed_namespace: namespace object created within parse_known_args()

        Returns
        -------
            OrderedDict: where keys are strings and values are either strings
            or lists
        """
        ...

    def convert_item_to_command_line_arg(self, action, key, value):  # -> list[Any]:
        """Converts a config file or env var key + value to a list of
        commandline args to append to the commandline.

        Args:
            action: The argparse Action object for this setting, or None if this
                config file setting doesn't correspond to any defined
                configargparse arg.
            key: string (config file key or env var name)
            value: parsed value of type string or list

        Returns
        -------
            list[str]: args
        """
        ...

    def get_possible_config_keys(self, action):  # -> list[Any]:
        """This method decides which actions can be set in a config file and
        what their keys will be. It returns a list of 0 or more config keys that
        can be used to set the given action's value in a config file.

        Returns
        -------
            list[str]: keys
        """
        ...

    def format_values(self):  # -> str:
        """Returns a string with all args and settings and where they came from
        (eg. commandline, config file, environment variable or default).

        Returns
        -------
            str: source to settings string
        """
        ...

    def print_values(self, file=...):  # -> None:
        """Prints the format_values() string (to sys.stdout or another file)."""
        ...

    def format_help(self):  # -> str:
        ...

def add_argument(self, *args, **kwargs):  # -> _StoreAction:
    """
    This method supports the same args as ArgumentParser.add_argument(..)
    as well as the additional args below.

    Arguments:
        env_var: If set, the value of this environment variable will override
            any config file or default values for this arg (but can itself
            be overridden on the commandline). Also, if auto_env_var_prefix is
            set in the constructor, this env var name will be used instead of
            the automatic name.
        is_config_file_arg: If True, this arg is treated as a config file path
            This provides an alternative way to specify config files in place of
            the ArgumentParser(fromfile_prefix_chars=..) mechanism.
            Default: False
        is_write_out_config_file_arg: If True, this arg will be treated as a
            config file path, and, when it is specified, will cause
            configargparse to write all current commandline args to this file
            as config options and then exit.
            Default: False

    Returns
    -------
        argparse.Action: the new argparse action
    """
    ...

def already_on_command_line(existing_args_list, potential_command_line_args, prefix_chars):  # -> bool:
    """Utility method for checking if any of the potential_command_line_args is
    already present in existing_args.

    Returns
    -------
        bool: already on command line?
    """
    ...

Action = argparse.Action
ArgumentDefaultsHelpFormatter = argparse.ArgumentDefaultsHelpFormatter
ArgumentError = argparse.ArgumentError
ArgumentTypeError = argparse.ArgumentTypeError
FileType = argparse.FileType
HelpFormatter = argparse.HelpFormatter
MetavarTypeHelpFormatter = argparse.MetavarTypeHelpFormatter
Namespace = argparse.Namespace
RawDescriptionHelpFormatter = argparse.RawDescriptionHelpFormatter
RawTextHelpFormatter = argparse.RawTextHelpFormatter
ONE_OR_MORE = ...
OPTIONAL = ...
PARSER = ...
REMAINDER = ...
SUPPRESS = ...
ZERO_OR_MORE = ...
initArgumentParser = ...
getArgumentParser = ...
getArgParser = ...
getParser = ...
get_arg_parser = ...
get_parser = ...
ArgParser = ArgumentParser
Parser = ArgumentParser
RawFormatter = RawDescriptionHelpFormatter
DefaultsFormatter = ArgumentDefaultsHelpFormatter
DefaultsRawFormatter = ArgumentDefaultsRawHelpFormatter
